// Path C full engine embedding vs official Qwen3VLEmbedder gate.
//
// This test consumes two reference files per production resolution, generated by
// tests/python_reference/gen_official_embedding.py from the real official
// Qwen3VLEmbedder public process() API:
//   /tmp/official_embed_mm_<H>x<W>.bin   [int64 dim][float32 * dim]
//   /tmp/official_tokens_mm_<H>x<W>.bin  [int32 count][int64 * count]
//
// The token bin comes from the same official preprocess call/conversation as the
// embedding, so C++ does not hand-write the chat template tokens.

#include "atb_llm/types.h"
#include "atb_llm/engine.h"
#include "adapters/qwen3vl_embedding/qwen3vl_config.h"
#include "adapters/qwen3vl_embedding/qwen3vl_preprocess.h"
#include "utils/dotenv.h"
#include "utils/float_utils.h"
#include "log/logger.h"
#include "test_env.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <sstream>
#include <string>
#include <vector>

#define IS_OK(s) ((s) == atb_llm::STATUS_OK)

namespace {

static const std::string MODEL_DIR = GetModelDir();
static constexpr int32_t kChannels = 3;
static constexpr double kCosThreshold = 0.99;

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) return false;
        int64_t ndim = 0;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1 || ndim < 0) {
            fclose(f);
            return false;
        }
        shape.resize(static_cast<size_t>(ndim));
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[static_cast<size_t>(i)], sizeof(int64_t), 1, f) != 1) {
                fclose(f);
                return false;
            }
            total *= shape[static_cast<size_t>(i)];
        }
        data.resize(static_cast<size_t>(total));
        if (fread(data.data(), sizeof(float), static_cast<size_t>(total), f) !=
            static_cast<size_t>(total)) {
            fclose(f);
            return false;
        }
        fclose(f);
        return true;
    }
};

bool LoadTokens(const std::string& path, std::vector<int64_t>& tokens) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return false;
    int32_t count = 0;
    if (fread(&count, sizeof(int32_t), 1, f) != 1 || count <= 0) {
        fclose(f);
        return false;
    }
    tokens.resize(static_cast<size_t>(count));
    if (fread(tokens.data(), sizeof(int64_t), static_cast<size_t>(count), f) !=
        static_cast<size_t>(count)) {
        fclose(f);
        return false;
    }
    fclose(f);
    return true;
}

bool LoadEmbedding(const std::string& path, std::vector<float>& embedding) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return false;
    int64_t dim = 0;
    if (fread(&dim, sizeof(int64_t), 1, f) != 1 || dim <= 0) {
        fclose(f);
        return false;
    }
    embedding.resize(static_cast<size_t>(dim));
    if (fread(embedding.data(), sizeof(float), static_cast<size_t>(dim), f) !=
        static_cast<size_t>(dim)) {
        fclose(f);
        return false;
    }
    fclose(f);
    return true;
}

std::vector<float> ResultToFp32(const atb_llm::InferResult& r) {
    int64_t dim = r.shape.empty() ? 0 : r.shape[0];
    std::vector<float> out(static_cast<size_t>(dim));
    if (r.dtype == ACL_FLOAT16) {
        const uint16_t* d = r.As<uint16_t>();
        for (int64_t i = 0; i < dim; i++) {
            out[static_cast<size_t>(i)] = atb_llm::Fp16ToF32(d[i]);
        }
    } else if (r.dtype == ACL_FLOAT) {
        const float* d = r.As<float>();
        out.assign(d, d + dim);
    } else {
        LOG_ERROR("ResultToFp32: unexpected dtype %d", static_cast<int>(r.dtype));
        out.clear();
    }
    return out;
}

std::vector<uint8_t> ToUint8Image(const LoadedArrayF32& input) {
    std::vector<uint8_t> image(input.data.size());
    for (size_t i = 0; i < input.data.size(); i++) {
        float v = std::round(input.data[i]);
        v = std::min(255.0f, std::max(0.0f, v));
        image[i] = static_cast<uint8_t>(v);
    }
    return image;
}

double CosineSim(const float* a, const float* b, int64_t n) {
    if (n <= 0) return 0.0;
    double dot = 0.0;
    double na = 0.0;
    double nb = 0.0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * static_cast<double>(b[i]);
        na += static_cast<double>(a[i]) * static_cast<double>(a[i]);
        nb += static_cast<double>(b[i]) * static_cast<double>(b[i]);
    }
    if (na <= 0.0 || nb <= 0.0) return 0.0;
    return dot / (std::sqrt(na) * std::sqrt(nb));
}

int64_t CountToken(const std::vector<int64_t>& tokens, int64_t token_id) {
    int64_t n = 0;
    for (size_t i = 0; i < tokens.size(); i++) {
        if (tokens[i] == token_id) n++;
    }
    return n;
}

}  // namespace

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;

    if (MODEL_DIR.empty()) {
        std::fprintf(stderr,
            "QWEN3VL_EMB_MODEL_DIR is not set. Source .env via build_and_test.sh "
            "or export the variable.\n");
        return 1;
    }

    atb_llm::EngineConfig cfg;
    cfg.model_dir = MODEL_DIR;
    cfg.buffer_size = 15LL * 1024 * 1024 * 1024;
    cfg.device_id = 0;

    std::unique_ptr<atb_llm::LLMEngine> engine;
    atb_llm::Status s = atb_llm::LLMEngine::Create(cfg, engine);
    if (!IS_OK(s) || !engine) {
        LOG_ERROR("Failed to create engine: %d", static_cast<int>(s));
        return 1;
    }

    atb_llm::adapters::Qwen3VLConfig pp_cfg;
    s = atb_llm::adapters::LoadQwen3VLConfig(MODEL_DIR, pp_cfg);
    if (!IS_OK(s)) {
        LOG_ERROR("LoadQwen3VLConfig failed: %d", static_cast<int>(s));
        return 1;
    }

    struct Case { int32_t h; int32_t w; };
    std::vector<Case> cases;
    {
        std::string cases_str = GetEnv("OFFICIAL_EMBED_CASES", "416x672,720x1280,1080x1920,1440x2560");
        std::istringstream iss(cases_str);
        std::string token;
        while (std::getline(iss, token, ',')) {
            // Trim whitespace and brackets
            size_t start = 0;
            while (start < token.size() &&
                   (token[start] == ' ' || token[start] == '\t' || token[start] == '['))
                start++;
            size_t end = token.size();
            while (end > start &&
                   (token[end - 1] == ' ' || token[end - 1] == '\t' || token[end - 1] == ']'))
                end--;
            token = token.substr(start, end - start);
            if (token.empty()) continue;
            size_t xpos = token.find('x');
            if (xpos == std::string::npos) { LOG_WARN("[OFFICIAL EMBED GATE] skipping invalid token '%s' (no 'x' separator)", token.c_str()); continue; }
            int32_t h = std::stoi(token.substr(0, xpos));
            int32_t w = std::stoi(token.substr(xpos + 1));
            cases.push_back({h, w});
        }
    }

    if (cases.empty()) {
        LOG_ERROR("[OFFICIAL EMBED GATE] FAIL: OFFICIAL_EMBED_CASES resolved to an empty case list");
        return 1;
    }

    int failures = 0;
    for (const auto& c : cases) {
        std::string res = std::to_string(c.h) + "x" + std::to_string(c.w);
        std::string input_path = "/tmp/bicubic_prod_" + res + "_input.bin";
        std::string token_path = "/tmp/official_tokens_mm_" + res + ".bin";
        std::string embed_path = "/tmp/official_embed_mm_" + res + ".bin";

        LoadedArrayF32 input;
        if (!input.Load(input_path) || input.shape.size() != 3 ||
            input.shape[0] != kChannels || input.shape[1] != c.h || input.shape[2] != c.w) {
            LOG_ERROR("[%s] missing/malformed shared input bin: %s", res.c_str(), input_path.c_str());
            failures++;
            continue;
        }

        std::vector<int64_t> tokens;
        if (!LoadTokens(token_path, tokens)) {
            LOG_ERROR("[%s] missing/malformed official token bin: %s", res.c_str(), token_path.c_str());
            failures++;
            continue;
        }

        std::vector<float> official;
        if (!LoadEmbedding(embed_path, official)) {
            LOG_ERROR("[%s] missing/malformed official embedding bin: %s", res.c_str(), embed_path.c_str());
            failures++;
            continue;
        }

        std::vector<uint8_t> image = ToUint8Image(input);

        int32_t factor = pp_cfg.pp_patch_size * pp_cfg.pp_merge_size;
        int32_t new_h = 0;
        int32_t new_w = 0;
        atb_llm::adapters::SmartResize(c.h, c.w, factor,
                                       pp_cfg.pp_min_pixels, pp_cfg.pp_max_pixels,
                                       new_h, new_w);
        int64_t grid_h = new_h / pp_cfg.pp_patch_size;
        int64_t grid_w = new_w / pp_cfg.pp_patch_size;
        int64_t merged_tokens = grid_h * grid_w / (pp_cfg.pp_merge_size * pp_cfg.pp_merge_size);
        int64_t image_tokens = CountToken(tokens, pp_cfg.image_token_id);
        if (image_tokens != merged_tokens) {
            LOG_ERROR("[%s] official token image count=%ld != expected merged_tokens=%ld "
                      "(resize %dx%d -> %dx%d)",
                      res.c_str(), static_cast<long>(image_tokens),
                      static_cast<long>(merged_tokens), c.h, c.w, new_h, new_w);
            failures++;
            continue;
        }

        atb_llm::InferRequest req;
        req.mode = atb_llm::InputMode::IMAGE_AND_TEXT;
        req.text.input_ids = tokens.data();
        req.text.batch_size = 1;
        req.text.seq_length = static_cast<int64_t>(tokens.size());
        req.raw_image.data = image.data();
        req.raw_image.channels = kChannels;
        req.raw_image.height = c.h;
        req.raw_image.width = c.w;

        atb_llm::InferResult result;
        atb_llm::StageTimings timings{};
        s = engine->EncodeWithTiming(req, result, timings);
        if (!IS_OK(s)) {
            LOG_ERROR("[%s] EncodeWithTiming failed: %d", res.c_str(), static_cast<int>(s));
            failures++;
            continue;
        }

        std::vector<float> cpp = ResultToFp32(result);
        if (cpp.size() != official.size() || cpp.empty()) {
            LOG_ERROR("[%s] embedding dim mismatch/empty: cpp=%zu official=%zu",
                      res.c_str(), cpp.size(), official.size());
            failures++;
            continue;
        }

        double cos = CosineSim(cpp.data(), official.data(), static_cast<int64_t>(cpp.size()));
        LOG_INFO("[OFFICIAL EMBED GATE] %s tokens=%zu image_tokens=%ld "
                 "resize=%dx%d->%dx%d dim=%zu cos=%.6f preprocess_ms=%.3f e2e_ms=%.3f",
                 res.c_str(), tokens.size(), static_cast<long>(image_tokens),
                 c.h, c.w, new_h, new_w, cpp.size(), cos,
                 timings.preprocess_ms, timings.e2e_ms);

        if (cos < kCosThreshold) {
            LOG_ERROR("[%s] FAIL: cosine %.6f < %.2f", res.c_str(), cos, kCosThreshold);
            failures++;
        }
        if (timings.preprocess_ms <= 0.0) {
            LOG_ERROR("[%s] FAIL: path C preprocess_ms not recorded (%.3f)",
                      res.c_str(), timings.preprocess_ms);
            failures++;
        }
    }

    if (failures != 0) {
        LOG_ERROR("[OFFICIAL EMBED GATE] FAIL: %d issue(s)", failures);
        return 1;
    }

    LOG_INFO("[OFFICIAL EMBED GATE] PASS: all path C embeddings cos >= %.2f", kCosThreshold);
    return 0;
}
