/* 
根据环境变量LOG_LEVEL
有
0 LOD_D CHECK_BOOL_D
1 LOG_I CHECK_BOOL_I
2 LOG_W CHECK_BOOL_W
3 LOG_E CHECK_BOOL_E

CHECK_ACL_STATUS acl_status != ACL_SUCCESS LOG_E
CHECK_ATB_STATUS atb_status != atb::NO_ERROR LOG_E


*/