/**
 * P10-B precision spike: aclnnUpsampleBicubic2d vs PIL reference.
 *
 * PURPOSE (architect decision gate, NOT a permanent regression test yet):
 *   aclnnUpsampleBicubic2d has torch semantics (a=-0.75 Mitchell, no
 *   antialias, align_corners=False). The authoritative Qwen3-VL resize is
 *   PIL BICUBIC (a=-0.5 Catmull-Rom + antialias). This spike measures the
 *   actual cosine against the PIL ground truth so the architect can decide:
 *   engineer P10-B (if cos>=0.99 vs PIL) or abandon aclnn and go to P10-C.
 *
 * References (generated by gen_cpu_reference.py --stage bicubic_preprocess):
 *   /tmp/bicubic_<name>_input.bin        — float32, 0..255 (quantized uint8)
 *   /tmp/bicubic_<name>_pil_output.bin   — PIL.Image.resize(BICUBIC)
 *   /tmp/bicubic_<name>_output.bin       — Python translation of C++ Catmull-Rom
 *                                          (SMALL cases only; prod cases are
 *                                          PIL-only — see pil_only in gen script)
 *
 * Cases:
 *   - small (2x2/4x4/8x8): boundary band dominates, directional signal only
 *   - PROD (416x672 / 720x1280 / 1080x1920 / 1440x2560): real engine sizes,
 *     smart_resize'd output dims, interior dominates — the regime that matters.
 *
 * aclnn takes fp16 NCHW; references are float32 0..255 (raw resize, no
 * normalize), so scale matches directly.
 *
 * Run: ./build/test_aclnn_bicubic_spike
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

#include "atb_llm/runtime.h"
#include "engine/runtime_impl.h"
#include "components/vision/aclnn_bicubic_resize.h"
#include "utils/float_utils.h"    // Fp32ToFp16, Fp16ToF32
#include "log/logger.h"

#include "acl/acl.h"

#include <cstdio>
#include <cstdint>
#include <vector>
#include <cmath>
#include <string>

#define IS_OK(s) ((s) == atb_llm::STATUS_OK)

namespace {

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;
    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) return false;
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(float), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

double CosineSim(const float* a, const float* b, int64_t n) {
    if (n <= 0) return 0.0;
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na  += static_cast<double>(a[i]) * a[i];
        nb  += static_cast<double>(b[i]) * b[i];
    }
    return dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12);
}

float MaxAbsDiff(const float* a, const float* b, int64_t n) {
    float m = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = std::fabs(a[i] - b[i]);
        if (d > m) m = d;
    }
    return m;
}

/// Run aclnn bicubic (or AA variant) on one case and compare vs the PIL reference.
/// Output dims are read from the PIL reference's .bin shape (C,H,W), so the
/// test stays in sync with smart_resize automatically.
/// Returns the PIL cosine (0.0 if the case was skipped).
double RunCase(atb_llm::IRuntime* runtime, const std::string& name,
               int32_t channels, int32_t in_h, int32_t in_w, bool prod,
               bool use_aa = false) {
    std::string in_path  = "/tmp/bicubic_" + name + "_input.bin";
    std::string pil_path = "/tmp/bicubic_" + name + "_pil_output.bin";

    LoadedArrayF32 in_ref, pil_ref;
    if (!in_ref.Load(in_path) || !pil_ref.Load(pil_path)) {
        LOG_ERROR("  [MISSING] %s: bin files missing — run "
                  "'python tests/gen_cpu_reference.py --stage bicubic_preprocess'", name.c_str());
        return 0.0;
    }
    if (pil_ref.shape.size() != 3) {
        LOG_ERROR("  [MISSING] %s: unexpected PIL ref ndim=%zu", name.c_str(), pil_ref.shape.size());
        return 0.0;
    }
    // Cross-check: validate that the input .bin C-dim matches the caller-declared channels.
    if (in_ref.shape.size() != 3 ||
        static_cast<int32_t>(in_ref.shape[0]) != channels) {
        LOG_ERROR("  [MISSING] %s: input C=%ld != declared channels=%d",
                  name.c_str(),
                  in_ref.shape.empty() ? 0 : static_cast<long>(in_ref.shape[0]),
                  channels);
        return 0.0;
    }
    int32_t out_h = static_cast<int32_t>(pil_ref.shape[1]);
    int32_t out_w = static_cast<int32_t>(pil_ref.shape[2]);

    int64_t in_elems  = static_cast<int64_t>(channels) * in_h  * in_w;
    int64_t out_elems = static_cast<int64_t>(channels) * out_h * out_w;
    if (static_cast<int64_t>(in_ref.data.size())  != in_elems ||
        static_cast<int64_t>(pil_ref.data.size()) != out_elems) {
        LOG_ERROR("  [MISSING] %s: bin size mismatch (in=%zu exp %ld, pil=%zu exp %ld)",
                  name.c_str(), in_ref.data.size(), in_elems,
                  pil_ref.data.size(), out_elems);
        return 0.0;
    }

    std::vector<uint16_t> in_fp16(in_elems);
    for (int64_t i = 0; i < in_elems; i++) {
        in_fp16[i] = atb_llm::Fp32ToFp16(in_ref.data[i]);
    }

    void* d_in  = nullptr;
    void* d_out = nullptr;
    size_t in_bytes  = in_elems  * sizeof(uint16_t);
    size_t out_bytes = out_elems * sizeof(uint16_t);
    REQUIRE(aclrtMalloc(&d_in,  in_bytes,  ACL_MEM_MALLOC_HUGE_FIRST) == ACL_SUCCESS);
    REQUIRE(aclrtMalloc(&d_out, out_bytes, ACL_MEM_MALLOC_HUGE_FIRST) == ACL_SUCCESS);
    REQUIRE(aclrtMemcpy(d_in, in_bytes, in_fp16.data(), in_bytes,
                        ACL_MEMCPY_HOST_TO_DEVICE) == ACL_SUCCESS);

    atb_llm::Status s;
    if (use_aa) {
        s = atb_llm::NpuBicubicResizeAA(
            runtime, d_in, channels, in_h, in_w, out_h, out_w, d_out);
    } else {
        s = atb_llm::NpuBicubicResize(
            runtime, d_in, channels, in_h, in_w, out_h, out_w, d_out);
    }
    REQUIRE(IS_OK(s));

    std::vector<uint16_t> out_fp16(out_elems);
    REQUIRE(aclrtMemcpy(out_fp16.data(), out_bytes, d_out, out_bytes,
                        ACL_MEMCPY_DEVICE_TO_HOST) == ACL_SUCCESS);
    std::vector<float> got(out_elems);
    for (int64_t i = 0; i < out_elems; i++) {
        got[i] = atb_llm::Fp16ToF32(out_fp16[i]);
    }

    double cos_pil = CosineSim(got.data(), pil_ref.data.data(), out_elems);
    float  diff_pil = MaxAbsDiff(got.data(), pil_ref.data.data(), out_elems);

    LOG_INFO("  [%s%s]%s in=%dx%dx%d -> %dx%d  |  vs PIL cos=%.6f max_diff=%.4f",
             prod ? "PROD " : "", name.c_str(),
             use_aa ? "(AA)" : "",
             channels, in_h, in_w, out_h, out_w, cos_pil, diff_pil);

    aclrtFree(d_in);
    aclrtFree(d_out);
    return cos_pil;
}

}  // namespace

TEST_CASE("aclnn-bicubic-spike: measure cosine vs PIL reference") {
    // CANN 9.0.0 docs: aclnnUpsampleBicubic2d supports BOTH Atlas training
    // (910B) and Atlas inference (310P) series. Run unconditionally.
    auto runtime = atb_llm::CreateRuntime(0, 1LL * 1024 * 1024 * 1024);
    REQUIRE(runtime);

    // ── Small cases (boundary-dominated, directional signal) ──
    LOG_INFO("=== small cases (FYI only — not a gate; gate applies to production cases only) ===");
    RunCase(runtime.get(), "random_8x8_to_16x16_3ch", 3, 8, 8, false);
    RunCase(runtime.get(), "2x2_to_4x4",              1, 2, 2, false);
    RunCase(runtime.get(), "4x4_to_2x2",              1, 4, 4, false);

    // ── Production-resolution cases (interior-dominated, the regime that matters) ──
    // Output dims come from the real smart_resize in gen_cpu_reference.py and
    // are read back from the PIL ref .bin shape (no hardcoding here).
    LOG_INFO("=== production-resolution cases ===");
    double cos_prod[4];
    cos_prod[0] = RunCase(runtime.get(), "prod_416x672",    3, 416,  672,  true);
    cos_prod[1] = RunCase(runtime.get(), "prod_720x1280",   3, 720,  1280, true);
    cos_prod[2] = RunCase(runtime.get(), "prod_1080x1920",  3, 1080, 1920, true);
    cos_prod[3] = RunCase(runtime.get(), "prod_1440x2560",  3, 1440, 2560, true);

    // NOTE: 1080x1920 and 1440x2560 are EXPECTED to FAIL — these are the
    // downsampling cases where non-AA bicubic aliases severely vs PIL.
    // The AA test case below passes all 4 (cos >= 0.99998), proving that
    // the anti-aliasing pre-filter rescues P10-B. These CHECKs remain as
    // permanent baseline evidence of WHY AA is required.
    //
    // ── Decision gate: production bar is cos>=0.99 vs PIL at ALL prod resolutions ──
    LOG_INFO("========================================================");
    LOG_INFO("[SPIKE GATE] cos (gate applies to production cases only): 416=%.4f 720=%.4f 1080=%.4f 1440=%.4f",
             cos_prod[0], cos_prod[1], cos_prod[2], cos_prod[3]);
    LOG_INFO("  all >= 0.99 -> engineer P10-B;  any < 0.99 -> abandon aclnn, go P10-C");
    LOG_INFO("========================================================");
    for (int i = 0; i < 4; i++) {
        CHECK(cos_prod[i] >= 0.99);
    }
}

TEST_CASE("aclnn-bicubic-spike-AA: measure AA variant on all 4 production resolutions") {
    // aclnnUpsampleBicubic2dAA adds an anti-aliasing pre-filter before bicubic
    // interpolation. This should match PIL's antialiased Catmull-Rom at all
    // production resolutions — not just the worst-case downsample.

    auto runtime = atb_llm::CreateRuntime(0, 1LL * 1024 * 1024 * 1024);
    REQUIRE(runtime);

    LOG_INFO("=== AA production-resolution cases ===");
    double cos_aa[4];
    cos_aa[0] = RunCase(runtime.get(), "prod_416x672",    3, 416,  672,  true, true);
    cos_aa[1] = RunCase(runtime.get(), "prod_720x1280",   3, 720,  1280, true, true);
    cos_aa[2] = RunCase(runtime.get(), "prod_1080x1920",  3, 1080, 1920, true, true);
    cos_aa[3] = RunCase(runtime.get(), "prod_1440x2560",  3, 1440, 2560, true, true);

    // ── Decision gate: AA variant must hit cos>=0.99 at ALL prod resolutions ──
    LOG_INFO("================================================================");
    LOG_INFO("[AA SPIKE GATE] cos: 416=%.6f 720=%.6f 1080=%.6f 1440=%.6f",
             cos_aa[0], cos_aa[1], cos_aa[2], cos_aa[3]);
    LOG_INFO("  all >= 0.99 -> AA rescues P10-B;  any < 0.99 -> go P10-C");
    LOG_INFO("================================================================");
    for (int i = 0; i < 4; i++) {
        CHECK(cos_aa[i] >= 0.99);
    }
}
