/**
 * Level 1 CPU pure-function tests: ComputePosEmbedInterp.
 *
 * NO NPU required — pure CPU bilinear interpolation + spatial-merge shuffle.
 * Compares against Python `fast_pos_embed_interpolate` reference generated by
 * `gen_cpu_reference.py --stage pos_embed`.
 *
 * Prerequisites:
 *     python tests/gen_cpu_reference.py --stage pos_embed
 *
 * Output files consumed:
 *     /tmp/cpu_pos_embed_src.bin            (fp16, num_grid^2 x hidden_size)
 *     /tmp/cpu_pos_embed_ref_typical.bin    (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_typical.bin   (int64, [[1, 8, 12]])
 *     /tmp/cpu_pos_embed_ref_small.bin      (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_small.bin     (int64, [[1, 2, 2]])
 *     /tmp/cpu_pos_embed_ref_multi.bin      (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_multi.bin     (int64, [[1, 4, 4], [1, 6, 8]])
 *
 * Run: ./test_pos_embed_cpu
 */

#include "components/vision/pos_embed_interp.h"
#include "utils/float_utils.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>

namespace {

// ── Binary file loaders ──────────────────────────────────────
// Format: [ndim: int64] [shape: int64[ndim]] [data: raw]

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(float), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayI64 {
    std::vector<int64_t> shape;
    std::vector<int64_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(int64_t), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayFp16 {
    std::vector<int64_t> shape;
    std::vector<uint16_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(uint16_t), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

// ── Metrics ──────────────────────────────────────────────────
float CosineSim(const float* a, const float* b, int64_t n) {
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na  += static_cast<double>(a[i]) * a[i];
        nb  += static_cast<double>(b[i]) * b[i];
    }
    return static_cast<float>(dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12));
}

float MaxAbsDiff(const float* a, const float* b, int64_t n) {
    float max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = std::fabs(a[i] - b[i]);
        if (d > max_d) max_d = d;
    }
    return max_d;
}

int64_t TotalPatches(const int64_t* grid_thw, int64_t num_images) {
    int64_t total = 0;
    for (int64_t i = 0; i < num_images; i++) {
        total += grid_thw[i * 3 + 0] * grid_thw[i * 3 + 1] * grid_thw[i * 3 + 2];
    }
    return total;
}

// Helper: load src + grid + ref, run ComputePosEmbedInterp, return (cos, max_diff).
// On any load failure, returns cos = -2 to signal SKIP.
struct CaseResult {
    bool loaded = false;
    int64_t num_patches = 0;
    int64_t hidden_size = 0;
    float cosine = 0.0f;
    float max_diff = 0.0f;
};

CaseResult RunCase(const std::string& src_path,
                   const std::string& grid_path,
                   const std::string& ref_path,
                   int32_t merge_size) {
    CaseResult r;
    LoadedArrayFp16 src;
    LoadedArrayI64  grid;
    LoadedArrayF32  ref;

    if (!src.Load(src_path) || !grid.Load(grid_path) || !ref.Load(ref_path)) {
        return r;  // loaded = false
    }
    r.loaded = true;

    // src shape: (num_grid^2, hidden_size)
    if (src.shape.size() != 2) {
        LOG_ERROR("src shape must be 2D, got %zu", src.shape.size());
        return r;
    }
    int64_t num_grid_sq = src.shape[0];
    int32_t hidden_size = static_cast<int32_t>(src.shape[1]);
    int32_t num_grid    = static_cast<int32_t>(std::sqrt(static_cast<double>(num_grid_sq)));
    if (static_cast<int64_t>(num_grid) * num_grid != num_grid_sq) {
        LOG_ERROR("src rows %ld is not a perfect square", num_grid_sq);
        return r;
    }

    // grid shape: (num_images, 3)
    if (grid.shape.size() != 2 || grid.shape[1] != 3) {
        LOG_ERROR("grid shape must be (N, 3)");
        return r;
    }
    int64_t num_images = grid.shape[0];
    int64_t total_patches = TotalPatches(grid.data.data(), num_images);

    r.num_patches = total_patches;
    r.hidden_size = hidden_size;

    // Allocate output buffer
    std::vector<uint16_t> out(total_patches * hidden_size, 0);

    atb_llm::components::ComputePosEmbedInterp(
        src.data.data(), hidden_size, num_grid, merge_size,
        grid.data.data(), num_images, out.data());

    // Convert C++ fp16 output to fp32 for comparison
    std::vector<float> out_f32(total_patches * hidden_size);
    for (int64_t i = 0; i < total_patches * hidden_size; i++) {
        out_f32[i] = atb_llm::Fp16ToF32(out[i]);
    }

    // Verify ref shape matches
    int64_t ref_total = total_patches * hidden_size;
    int64_t ref_n = 1;
    for (auto s : ref.shape) ref_n *= s;
    if (ref_n != ref_total) {
        LOG_ERROR("ref total %ld != expected %ld", ref_n, ref_total);
        return r;
    }

    r.cosine   = CosineSim(out_f32.data(), ref.data.data(), ref_total);
    r.max_diff = MaxAbsDiff(out_f32.data(), ref.data.data(), ref_total);
    return r;
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: typical case — grid [1, 8, 12], merge=2
// ═══════════════════════════════════════════════════════════════
static bool TestTypical() {
    LOG_INFO("=== Test 1: ComputePosEmbedInterp — typical grid [1, 8, 12] ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_typical.bin",
                     "/tmp/cpu_pos_embed_ref_typical.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    bool pass = (r.cosine > 0.999f);
    LOG_INFO("  [%s] typical case", pass ? "PASS" : "FAIL");
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: boundary case — minimum grid [1, 2, 2], merge=2
// (single merged block, one merge_size x merge_size patch)
// ═══════════════════════════════════════════════════════════════
static bool TestBoundarySmall() {
    LOG_INFO("\n=== Test 2: ComputePosEmbedInterp — boundary grid [1, 2, 2] ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_small.bin",
                     "/tmp/cpu_pos_embed_ref_small.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    // Expect 4 patches (h=2, w=2 → 1 merged block × 4 spatial-merge tokens)
    bool count_ok = (r.num_patches == 4);
    bool pass = count_ok && (r.cosine > 0.999f);
    LOG_INFO("  [%s] boundary case (patches=%ld, expected=4)",
             pass ? "PASS" : "FAIL", r.num_patches);
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: multi-image — grids [1,4,4] + [1,6,8], merge=2
// ═══════════════════════════════════════════════════════════════
static bool TestMultiImage() {
    LOG_INFO("\n=== Test 3: ComputePosEmbedInterp — multi-image ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_multi.bin",
                     "/tmp/cpu_pos_embed_ref_multi.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    // Expected: image0 = 4*4 = 16, image1 = 6*8 = 48, total = 64 patches
    int64_t expected = 16 + 48;
    bool count_ok = (r.num_patches == expected);
    bool pass = count_ok && (r.cosine > 0.999f);
    LOG_INFO("  [%s] multi-image case (patches=%ld, expected=%ld)",
             pass ? "PASS" : "FAIL", r.num_patches, expected);
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 4: h=1 edge case — grid [1, 1, 4], merge=1
// Exercises the divide-by-zero guard (h<=1 → fy=0.0f).
// ═══════════════════════════════════════════════════════════════
static bool TestH1EdgeCase() {
    LOG_INFO("\n=== Test 4: ComputePosEmbedInterp — h=1 edge case ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 1;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    // Create synthetic fp16 source: fill with a simple ramp pattern
    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    // grid_thw = [[1, 1, 4]] — single image, h=1, w=4
    std::vector<int64_t> grid = {1, 1, 4};
    int64_t num_images = 1;
    int64_t total_patches = TotalPatches(grid.data(), num_images);  // 1*1*4 = 4

    std::vector<uint16_t> out(total_patches * hidden, 0xFFFF);  // fill with NaN sentinel
    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    // Verify output is finite (no NaN, no inf)
    bool ok = true;
    for (int64_t i = 0; i < total_patches * hidden; i++) {
        float v = atb_llm::Fp16ToF32(out[i]);
        if (!std::isfinite(v)) {
            LOG_ERROR("  FAIL: out[%ld] = %f (non-finite)", i, v);
            ok = false;
            break;
        }
    }
    LOG_INFO("  patches=%ld hidden=%d all_finite=%s",
             total_patches, hidden, ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 5: w=1 edge case — grid [1, 4, 1], merge=1
// Exercises the divide-by-zero guard (w<=1 → fx=0.0f).
// ═══════════════════════════════════════════════════════════════
static bool TestW1EdgeCase() {
    LOG_INFO("\n=== Test 5: ComputePosEmbedInterp — w=1 edge case ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 1;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    // grid_thw = [[1, 4, 1]] — single image, h=4, w=1
    std::vector<int64_t> grid = {1, 4, 1};
    int64_t num_images = 1;
    int64_t total_patches = TotalPatches(grid.data(), num_images);  // 1*4*1 = 4

    std::vector<uint16_t> out(total_patches * hidden, 0xFFFF);
    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    bool ok = true;
    for (int64_t i = 0; i < total_patches * hidden; i++) {
        float v = atb_llm::Fp16ToF32(out[i]);
        if (!std::isfinite(v)) {
            LOG_ERROR("  FAIL: out[%ld] = %f (non-finite)", i, v);
            ok = false;
            break;
        }
    }
    LOG_INFO("  patches=%ld hidden=%d all_finite=%s",
             total_patches, hidden, ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 6: single pixel — grid [1, 1, 1], merge=1
// Minimum possible dimensions. Both h=1 and w=1 exercise both guards.
// ═══════════════════════════════════════════════════════════════
static bool TestSinglePixel() {
    LOG_INFO("\n=== Test 6: ComputePosEmbedInterp — single pixel (h=1, w=1) ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 1;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    // grid_thw = [[1, 1, 1]] — single pixel
    std::vector<int64_t> grid = {1, 1, 1};
    int64_t num_images = 1;
    int64_t total_patches = TotalPatches(grid.data(), num_images);  // 1

    std::vector<uint16_t> out(total_patches * hidden, 0xFFFF);
    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    // Verify one output patch, all finite
    bool ok = (total_patches == 1);
    if (!ok) {
        LOG_ERROR("  FAIL: expected 1 patch, got %ld", total_patches);
    }
    for (int64_t i = 0; i < total_patches * hidden; i++) {
        float v = atb_llm::Fp16ToF32(out[i]);
        if (!std::isfinite(v)) {
            LOG_ERROR("  FAIL: out[%ld] = %f (non-finite)", i, v);
            ok = false;
            break;
        }
    }
    LOG_INFO("  patches=%ld hidden=%d %s",
             total_patches, hidden, ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 7: num_images=0 — empty grid_thw
// Should handle gracefully without crash or output modification.
// ═══════════════════════════════════════════════════════════════
static bool TestNumImagesZero() {
    LOG_INFO("\n=== Test 7: ComputePosEmbedInterp — num_images=0 ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 2;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    int64_t num_images = 0;
    // Allocate a small output buffer (should not be touched)
    std::vector<uint16_t> out(16, 0xABCD);  // sentinel
    // grid_thw pointer is unused when num_images=0, pass a dummy
    std::vector<int64_t> grid = {0, 0, 0};

    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    // Verify output was not modified (sentinels intact)
    bool ok = true;
    for (size_t i = 0; i < out.size(); i++) {
        if (out[i] != 0xABCD) {
            LOG_ERROR("  FAIL: out[%zu] modified (0x%04X != 0xABCD)",
                      i, out[i]);
            ok = false;
            break;
        }
    }
    LOG_INFO("  num_images=0 output_untouched=%s", ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 8: temporal > 1 — grid [2, 4, 4], merge=2
// Tests the temporal repetition path (lines 83-87 of pos_embed_interp.cpp).
// The first temporal frame is computed via interpolation+merge; subsequent
// frames are memcpy'd from the first.
// ═══════════════════════════════════════════════════════════════
static bool TestTemporalGt1() {
    LOG_INFO("\n=== Test 8: ComputePosEmbedInterp — temporal=2, grid [2, 4, 4] ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 2;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    // grid_thw = [[2, 4, 4]] — t=2 temporal frames, 4x4 spatial
    std::vector<int64_t> grid = {2, 4, 4};
    int64_t num_images = 1;
    int64_t total_patches = TotalPatches(grid.data(), num_images);  // 2*4*4 = 32

    std::vector<uint16_t> out(total_patches * hidden, 0xFFFF);
    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    // With merge_size=2, h=4 → merged_h=2, w=4 → merged_w=2
    // Spatial merge writes 2*2*2*2 = 16 patches for frame 0
    // Temporal repetition copies those 16 patches to frame 1
    int64_t frame_size = 4 * 4;  // h * w = 16 patches per frame
    bool ok = true;

    // Verify all output is finite
    for (int64_t i = 0; i < total_patches * hidden; i++) {
        float v = atb_llm::Fp16ToF32(out[i]);
        if (!std::isfinite(v)) {
            LOG_ERROR("  FAIL: out[%ld] = %f (non-finite)", i, v);
            ok = false;
            break;
        }
    }

    // Verify temporal copy: frame 1 (offset 16) should equal frame 0 (offset 0)
    if (ok) {
        for (int64_t p = 0; p < frame_size; p++) {
            for (int32_t d = 0; d < hidden; d++) {
                int64_t idx0 = p * hidden + d;
                int64_t idx1 = (frame_size + p) * hidden + d;
                if (out[idx0] != out[idx1]) {
                    LOG_ERROR("  FAIL: temporal mismatch at patch %ld dim %d "
                              "(frame0=0x%04X frame1=0x%04X)",
                              p, d, out[idx0], out[idx1]);
                    ok = false;
                    break;
                }
            }
            if (!ok) break;
        }
    }

    LOG_INFO("  patches=%ld hidden=%d frame_size=%ld temporal_ok=%s",
             total_patches, hidden, frame_size, ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 9: non-divisible merge_size — grid [1, 5, 5], merge=2
// h=5 and w=5 are not divisible by merge_size=2.
// The integer division on lines 61-62 truncates (merged_h=2, merged_w=2).
// 2*2*2*2 = 16 patches are written from a 5*5=25 patch grid — the rightmost
// column and bottommost row of each merge block are silently dropped.
// ═══════════════════════════════════════════════════════════════
static bool TestNonDivisibleMerge() {
    LOG_INFO("\n=== Test 9: ComputePosEmbedInterp — non-divisible merge [1, 5, 5], merge=2 ===");

    constexpr int32_t num_grid = 4;
    constexpr int32_t hidden = 8;
    constexpr int32_t merge_size = 2;
    constexpr int64_t num_grid_sq = num_grid * num_grid;

    std::vector<uint16_t> src(num_grid_sq * hidden);
    for (int64_t i = 0; i < num_grid_sq * hidden; i++) {
        float v = static_cast<float>(i % 37) * 0.05f - 0.5f;
        src[i] = atb_llm::Fp32ToFp16(v);
    }

    // grid_thw = [[1, 5, 5]]
    std::vector<int64_t> grid = {1, 5, 5};
    int64_t num_images = 1;
    int64_t total_patches = TotalPatches(grid.data(), num_images);  // 1*5*5 = 25

    // Fill output with QNaN sentinel (0x7E00) to detect unwritten positions
    constexpr uint16_t kSentinel = 0x7E00;
    std::vector<uint16_t> out(total_patches * hidden, kSentinel);
    atb_llm::components::ComputePosEmbedInterp(
        src.data(), hidden, num_grid, merge_size,
        grid.data(), num_images, out.data());

    // Expected written patches: merged_h=2, merged_w=2, merge_size=2, merge_size=2
    // → 2*2*2*2 = 16 patches
    int64_t expected_written = 2 * 2 * merge_size * merge_size;  // 16

    // Verify that the written region (first expected_written patches) is finite,
    // and the remainder (expected_written..24) still has sentinel (0x7E00 = QNaN).
    bool ok = true;
    for (int64_t p = 0; p < total_patches; p++) {
        for (int32_t d = 0; d < hidden; d++) {
            int64_t idx = p * hidden + d;
            if (p < expected_written) {
                float v = atb_llm::Fp16ToF32(out[idx]);
                if (!std::isfinite(v)) {
                    LOG_ERROR("  FAIL: written patch %ld dim %d = %f (non-finite)",
                              p, d, v);
                    ok = false;
                    break;
                }
            } else {
                if (out[idx] != kSentinel) {
                    LOG_ERROR("  FAIL: unwritten patch %ld dim %d raw=0x%04X "
                              "(expected sentinel 0x%04X)",
                              p, d, out[idx], kSentinel);
                    ok = false;
                    break;
                }
            }
        }
        if (!ok) break;
    }

    LOG_INFO("  total=%ld written=%ld unwritten=%ld %s",
             total_patches, expected_written,
             total_patches - expected_written, ok ? "PASS" : "FAIL");
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== ComputePosEmbedInterp CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++; if (TestTypical())          passed++;
    total++; if (TestBoundarySmall())    passed++;
    total++; if (TestMultiImage())       passed++;
    total++; if (TestH1EdgeCase())       passed++;
    total++; if (TestW1EdgeCase())       passed++;
    total++; if (TestSinglePixel())      passed++;
    total++; if (TestNumImagesZero())    passed++;
    total++; if (TestTemporalGt1())      passed++;
    total++; if (TestNonDivisibleMerge()) passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
