/**
 * Level 1 CPU pure-function tests: ComputePosEmbedInterp.
 *
 * NO NPU required — pure CPU bilinear interpolation + spatial-merge shuffle.
 * Compares against Python `fast_pos_embed_interpolate` reference generated by
 * `gen_cpu_reference.py --stage pos_embed`.
 *
 * Prerequisites:
 *     python tests/gen_cpu_reference.py --stage pos_embed
 *
 * Output files consumed:
 *     /tmp/cpu_pos_embed_src.bin            (fp16, num_grid^2 x hidden_size)
 *     /tmp/cpu_pos_embed_ref_typical.bin    (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_typical.bin   (int64, [[1, 8, 12]])
 *     /tmp/cpu_pos_embed_ref_small.bin      (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_small.bin     (int64, [[1, 2, 2]])
 *     /tmp/cpu_pos_embed_ref_multi.bin      (fp32, fp16-roundtrip reference)
 *     /tmp/cpu_pos_embed_grid_multi.bin     (int64, [[1, 4, 4], [1, 6, 8]])
 *
 * Run: ./test_pos_embed_cpu
 */

#include "components/vision/pos_embed_interp.h"
#include "utils/float_utils.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>

namespace {

// ── Binary file loaders ──────────────────────────────────────
// Format: [ndim: int64] [shape: int64[ndim]] [data: raw]

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(float), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayI64 {
    std::vector<int64_t> shape;
    std::vector<int64_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(int64_t), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayFp16 {
    std::vector<int64_t> shape;
    std::vector<uint16_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) { LOG_ERROR("Cannot open %s", path.c_str()); return false; }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(uint16_t), total, f) != static_cast<size_t>(total)) {
            fclose(f); return false;
        }
        fclose(f);
        return true;
    }
};

// ── Metrics ──────────────────────────────────────────────────
float CosineSim(const float* a, const float* b, int64_t n) {
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na  += static_cast<double>(a[i]) * a[i];
        nb  += static_cast<double>(b[i]) * b[i];
    }
    return static_cast<float>(dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12));
}

float MaxAbsDiff(const float* a, const float* b, int64_t n) {
    float max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = std::fabs(a[i] - b[i]);
        if (d > max_d) max_d = d;
    }
    return max_d;
}

int64_t TotalPatches(const int64_t* grid_thw, int64_t num_images) {
    int64_t total = 0;
    for (int64_t i = 0; i < num_images; i++) {
        total += grid_thw[i * 3 + 0] * grid_thw[i * 3 + 1] * grid_thw[i * 3 + 2];
    }
    return total;
}

// Helper: load src + grid + ref, run ComputePosEmbedInterp, return (cos, max_diff).
// On any load failure, returns cos = -2 to signal SKIP.
struct CaseResult {
    bool loaded = false;
    int64_t num_patches = 0;
    int64_t hidden_size = 0;
    float cosine = 0.0f;
    float max_diff = 0.0f;
};

CaseResult RunCase(const std::string& src_path,
                   const std::string& grid_path,
                   const std::string& ref_path,
                   int32_t merge_size) {
    CaseResult r;
    LoadedArrayFp16 src;
    LoadedArrayI64  grid;
    LoadedArrayF32  ref;

    if (!src.Load(src_path) || !grid.Load(grid_path) || !ref.Load(ref_path)) {
        return r;  // loaded = false
    }
    r.loaded = true;

    // src shape: (num_grid^2, hidden_size)
    if (src.shape.size() != 2) {
        LOG_ERROR("src shape must be 2D, got %zu", src.shape.size());
        return r;
    }
    int64_t num_grid_sq = src.shape[0];
    int32_t hidden_size = static_cast<int32_t>(src.shape[1]);
    int32_t num_grid    = static_cast<int32_t>(std::sqrt(static_cast<double>(num_grid_sq)));
    if (static_cast<int64_t>(num_grid) * num_grid != num_grid_sq) {
        LOG_ERROR("src rows %ld is not a perfect square", num_grid_sq);
        return r;
    }

    // grid shape: (num_images, 3)
    if (grid.shape.size() != 2 || grid.shape[1] != 3) {
        LOG_ERROR("grid shape must be (N, 3)");
        return r;
    }
    int64_t num_images = grid.shape[0];
    int64_t total_patches = TotalPatches(grid.data.data(), num_images);

    r.num_patches = total_patches;
    r.hidden_size = hidden_size;

    // Allocate output buffer
    std::vector<uint16_t> out(total_patches * hidden_size, 0);

    atb_llm::components::ComputePosEmbedInterp(
        src.data.data(), hidden_size, num_grid, merge_size,
        grid.data.data(), num_images, out.data());

    // Convert C++ fp16 output to fp32 for comparison
    std::vector<float> out_f32(total_patches * hidden_size);
    for (int64_t i = 0; i < total_patches * hidden_size; i++) {
        out_f32[i] = atb_llm::Fp16ToF32(out[i]);
    }

    // Verify ref shape matches
    int64_t ref_total = total_patches * hidden_size;
    int64_t ref_n = 1;
    for (auto s : ref.shape) ref_n *= s;
    if (ref_n != ref_total) {
        LOG_ERROR("ref total %ld != expected %ld", ref_n, ref_total);
        return r;
    }

    r.cosine   = CosineSim(out_f32.data(), ref.data.data(), ref_total);
    r.max_diff = MaxAbsDiff(out_f32.data(), ref.data.data(), ref_total);
    return r;
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: typical case — grid [1, 8, 12], merge=2
// ═══════════════════════════════════════════════════════════════
static bool TestTypical() {
    LOG_INFO("=== Test 1: ComputePosEmbedInterp — typical grid [1, 8, 12] ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_typical.bin",
                     "/tmp/cpu_pos_embed_ref_typical.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    bool pass = (r.cosine > 0.999f);
    LOG_INFO("  [%s] typical case", pass ? "PASS" : "FAIL");
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: boundary case — minimum grid [1, 2, 2], merge=2
// (single merged block, one merge_size x merge_size patch)
// ═══════════════════════════════════════════════════════════════
static bool TestBoundarySmall() {
    LOG_INFO("\n=== Test 2: ComputePosEmbedInterp — boundary grid [1, 2, 2] ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_small.bin",
                     "/tmp/cpu_pos_embed_ref_small.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    // Expect 4 patches (h=2, w=2 → 1 merged block × 4 spatial-merge tokens)
    bool count_ok = (r.num_patches == 4);
    bool pass = count_ok && (r.cosine > 0.999f);
    LOG_INFO("  [%s] boundary case (patches=%ld, expected=4)",
             pass ? "PASS" : "FAIL", r.num_patches);
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: multi-image — grids [1,4,4] + [1,6,8], merge=2
// ═══════════════════════════════════════════════════════════════
static bool TestMultiImage() {
    LOG_INFO("\n=== Test 3: ComputePosEmbedInterp — multi-image ===");

    auto r = RunCase("/tmp/cpu_pos_embed_src.bin",
                     "/tmp/cpu_pos_embed_grid_multi.bin",
                     "/tmp/cpu_pos_embed_ref_multi.bin",
                     /*merge_size=*/2);
    if (!r.loaded) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage pos_embed");
        return false;
    }

    LOG_INFO("  patches=%ld hidden=%ld  Cosine=%.6f  MaxDiff=%.6f",
             r.num_patches, r.hidden_size, r.cosine, r.max_diff);

    // Expected: image0 = 4*4 = 16, image1 = 6*8 = 48, total = 64 patches
    int64_t expected = 16 + 48;
    bool count_ok = (r.num_patches == expected);
    bool pass = count_ok && (r.cosine > 0.999f);
    LOG_INFO("  [%s] multi-image case (patches=%ld, expected=%ld)",
             pass ? "PASS" : "FAIL", r.num_patches, expected);
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== ComputePosEmbedInterp CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++; if (TestTypical())       passed++;
    total++; if (TestBoundarySmall()) passed++;
    total++; if (TestMultiImage())    passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
