/**
 * Level 1 CPU pure-function tests: float conversion utilities.
 *
 * Tests src/utils/float_utils.h:
 *   - FloatToUint32   (type-pun)
 *   - Fp16ToF32       (CANN aclFloat16ToFloat)
 *   - Fp32ToFp16      (CANN aclFloatToFloat16)
 *   - Bf16ToFp16      (bf16 → fp32 → fp16, round-to-nearest-even)
 *   - Bf16ToFp16Buffer
 *
 * NO NPU required — these are CPU-only conversions using acl host APIs.
 * Reference data generated by tests/gen_cpu_reference.py --stage float_utils.
 *
 * Historical bug context for Bf16ToFp16:
 *   The previous implementation used a bit-manipulation path that
 *   simply zeroed the low 3 fp16 mantissa bits when converting bf16
 *   → fp16. This caused systematic downward rounding bias. The
 *   current path goes bf16 → fp32 → fp16 via CANN APIs to get proper
 *   round-to-nearest-even.
 *
 * Run: ./test_float_utils
 */

#include "utils/float_utils.h"
#include "log/logger.h"

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <vector>
#include <string>
#include <limits>

namespace {

// ── Reference data loader ─────────────────────────────────────
// Binary format from gen_cpu_reference.py::gen_float_utils:
//   [count: int64]
//   [bf16_bits[count]: uint16]
//   [fp16_expected_from_bf16[count]: uint16]
//   [fp32_values[count]: float32]
//   [fp16_expected_from_fp32[count]: uint16]
//   [fp32_roundtrip_from_fp16[count]: float32]
struct FloatUtilsRef {
    int64_t count = 0;
    std::vector<uint16_t> bf16_bits;
    std::vector<uint16_t> fp16_from_bf16;
    std::vector<float>    fp32_values;
    std::vector<uint16_t> fp16_from_fp32;
    std::vector<float>    fp32_roundtrip;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        if (fread(&count, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }

        bf16_bits.resize(count);
        fp16_from_bf16.resize(count);
        fp32_values.resize(count);
        fp16_from_fp32.resize(count);
        fp32_roundtrip.resize(count);

        bool ok = true;
        ok &= (fread(bf16_bits.data(),      sizeof(uint16_t), count, f) == static_cast<size_t>(count));
        ok &= (fread(fp16_from_bf16.data(), sizeof(uint16_t), count, f) == static_cast<size_t>(count));
        ok &= (fread(fp32_values.data(),    sizeof(float),    count, f) == static_cast<size_t>(count));
        ok &= (fread(fp16_from_fp32.data(), sizeof(uint16_t), count, f) == static_cast<size_t>(count));
        ok &= (fread(fp32_roundtrip.data(), sizeof(float),    count, f) == static_cast<size_t>(count));
        fclose(f);
        return ok;
    }
};

// Determine if an fp16 raw-bit pattern represents NaN.
bool Fp16IsNan(uint16_t bits) {
    uint16_t exp = (bits >> 10) & 0x1F;
    uint16_t mant = bits & 0x3FF;
    return (exp == 0x1F) && (mant != 0);
}

bool Fp16IsInf(uint16_t bits) {
    uint16_t exp = (bits >> 10) & 0x1F;
    uint16_t mant = bits & 0x3FF;
    return (exp == 0x1F) && (mant == 0);
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: Fp32 ↔ Fp16 roundtrip on canonical values
// ═══════════════════════════════════════════════════════════════
static bool TestFp32Fp16Roundtrip() {
    LOG_INFO("=== Test 1: Fp32 ↔ Fp16 roundtrip ===");

    struct Case {
        const char* name;
        float value;
        float tol;   // tolerance after round-trip
    };
    // Tolerances are eps * |value| for fp16 (~0.001) where applicable.
    const Case cases[] = {
        {"zero",          0.0f,                  0.0f},
        {"one",           1.0f,                  0.0f},
        {"neg one",      -1.0f,                  0.0f},
        {"half",          0.5f,                  0.0f},
        {"two^16",        65536.0f,              1e30f},  // becomes inf or saturates — informational
        {"fp16 max",      65504.0f,              0.0f},
        {"denormal min",  5.96046e-08f,          1e-7f},
        {"normal min",    6.103515625e-05f,      1e-8f},
    };

    bool all_ok = true;
    for (const auto& c : cases) {
        uint16_t bits = atb_llm::Fp32ToFp16(c.value);
        float    back = atb_llm::Fp16ToF32(bits);

        bool ok = false;
        const char* note = "";
        if (std::isinf(c.value) || c.value >= 65520.0f) {
            // Edge: 65536 -> may become inf (0x7C00) or saturate to 65504 (0x7BFF)
            ok = std::isinf(back) || std::fabs(back - 65504.0f) < 1.0f;
            note = " (overflow edge — accept inf or saturated max)";
        } else if (std::fabs(c.value) < 1e-6f) {
            // Denormal/subnormal — relative tolerance not meaningful
            ok = std::fabs(back - c.value) <= c.tol;
        } else {
            float rel = std::fabs(back - c.value) / std::fabs(c.value);
            ok = rel <= 1e-3f;  // fp16 has ~3 decimal digits of precision
        }

        if (ok) {
            LOG_INFO("  [PASS] %s: %.8g → 0x%04x → %.8g%s",
                     c.name, c.value, bits, back, note);
        } else {
            LOG_ERROR("  [FAIL] %s: %.8g → 0x%04x → %.8g (mismatch)%s",
                      c.name, c.value, bits, back, note);
            all_ok = false;
        }
    }
    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: Bf16ToFp16 vs Python (numpy) ground truth
// ═══════════════════════════════════════════════════════════════
static bool TestBf16ToFp16AgainstPython() {
    LOG_INFO("\n=== Test 2: Bf16ToFp16 against Python ground truth ===");

    FloatUtilsRef ref;
    if (!ref.Load("/tmp/cpu_float_utils.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_float_utils.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage float_utils");
        return false;
    }

    bool all_ok = true;
    int strict_mismatch = 0;
    for (int64_t i = 0; i < ref.count; i++) {
        uint16_t bf16   = ref.bf16_bits[i];
        uint16_t expect = ref.fp16_from_bf16[i];
        uint16_t got    = atb_llm::Bf16ToFp16(bf16);
        float    src    = ref.fp32_values[i];

        // Treat NaN/NaN and Inf/Inf same-sign as equal.
        bool ok = (got == expect)
               || (Fp16IsNan(got) && Fp16IsNan(expect))
               || (Fp16IsInf(got) && Fp16IsInf(expect)
                   && ((got & 0x8000) == (expect & 0x8000)));

        // For values near fp16 overflow boundary (where numpy emits inf
        // but CANN may saturate to 65504), accept either inf or saturated max.
        if (!ok) {
            bool near_overflow = std::fabs(src) >= 65000.0f;
            if (near_overflow) {
                bool got_finite_max  = (got    == 0x7BFF || got    == 0xFBFF);
                bool got_inf         = Fp16IsInf(got);
                bool exp_finite_max  = (expect == 0x7BFF || expect == 0xFBFF);
                bool exp_inf         = Fp16IsInf(expect);
                if ((got_inf || got_finite_max) && (exp_inf || exp_finite_max)) {
                    ok = true;
                }
            }
        }

        if (ok) {
            LOG_INFO("  [PASS] src=%.8g  bf16=0x%04x  cpp=0x%04x  py=0x%04x",
                     src, bf16, got, expect);
        } else {
            LOG_ERROR("  [FAIL] src=%.8g  bf16=0x%04x  cpp=0x%04x  py=0x%04x  diff=%d",
                      src, bf16, got, expect,
                      static_cast<int>(got) - static_cast<int>(expect));
            all_ok = false;
            strict_mismatch++;
        }
    }
    LOG_INFO("  → %lld checks, %d strict mismatches", (long long)ref.count, strict_mismatch);
    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: Bf16ToFp16Buffer batch consistency
// ═══════════════════════════════════════════════════════════════
static bool TestBf16ToFp16Buffer() {
    LOG_INFO("\n=== Test 3: Bf16ToFp16Buffer batch conversion ===");

    FloatUtilsRef ref;
    if (!ref.Load("/tmp/cpu_float_utils.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_float_utils.bin not found");
        return false;
    }

    std::vector<uint16_t> out(ref.count);
    atb_llm::Bf16ToFp16Buffer(ref.bf16_bits.data(), out.data(),
                              static_cast<size_t>(ref.count));

    // Compare against per-element calls
    bool all_ok = true;
    int mismatches = 0;
    for (int64_t i = 0; i < ref.count; i++) {
        uint16_t single = atb_llm::Bf16ToFp16(ref.bf16_bits[i]);
        if (out[i] != single) {
            LOG_ERROR("  [FAIL] idx=%lld: buffer=0x%04x single=0x%04x",
                      (long long)i, out[i], single);
            all_ok = false;
            mismatches++;
        }
    }
    if (all_ok) {
        LOG_INFO("  [PASS] All %lld elements match per-element Bf16ToFp16 (idempotent)",
                 (long long)ref.count);
    } else {
        LOG_ERROR("  [FAIL] %d mismatches", mismatches);
    }
    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 4: Special values — +0, -0, +Inf, -Inf, NaN
// ═══════════════════════════════════════════════════════════════
static bool TestSpecialValues() {
    LOG_INFO("\n=== Test 4: Special values (zero/inf/nan) ===");

    bool all_ok = true;

    // +0 → fp16 → +0
    {
        uint16_t bits = atb_llm::Fp32ToFp16(0.0f);
        float    back = atb_llm::Fp16ToF32(bits);
        bool ok = (bits == 0x0000) && (back == 0.0f) && !std::signbit(back);
        LOG_INFO("  [%s] +0.0 → 0x%04x → %.1f", ok ? "PASS" : "FAIL", bits, back);
        if (!ok) all_ok = false;
    }

    // -0 → fp16 → -0 (sign bit must be preserved)
    {
        float neg_zero = -0.0f;
        uint16_t bits = atb_llm::Fp32ToFp16(neg_zero);
        float    back = atb_llm::Fp16ToF32(bits);
        bool ok = (bits == 0x8000) && (back == 0.0f) && std::signbit(back);
        LOG_INFO("  [%s] -0.0 → 0x%04x → %.1f (sign=%d)",
                 ok ? "PASS" : "FAIL", bits, back, std::signbit(back));
        if (!ok) all_ok = false;
    }

    // NOTE: CANN's aclFloatToFloat16 is documented to saturate Inf/NaN to the
    // maximum finite fp16 value (0x7bff = +65504, 0xfbff = -65504) rather than
    // producing IEEE-754 fp16 Inf (0x7c00) / NaN. This is a property of the
    // CANN host API, not a bug in our wrapper. The tests below assert this
    // actual saturating behaviour so that any future change to the CANN API
    // (or to our wrapper) is caught immediately.
    //
    // In production, model weights are normal finite values; Inf/NaN inputs
    // would already indicate upstream corruption, so the saturating behaviour
    // is acceptable for our usage.

    // +Inf → saturate to max-finite fp16 (0x7bff = 65504)
    {
        float inf = std::numeric_limits<float>::infinity();
        uint16_t bits = atb_llm::Fp32ToFp16(inf);
        float    back = atb_llm::Fp16ToF32(bits);
        bool ok = (bits == 0x7bff) && std::isfinite(back) && back > 0.0f;
        LOG_INFO("  [%s] +inf → 0x%04x → %.3g (CANN saturates to max-finite)",
                 ok ? "PASS" : "FAIL", bits, back);
        if (!ok) all_ok = false;
    }

    // -Inf → saturate to -max-finite fp16 (0xfbff = -65504)
    {
        float ninf = -std::numeric_limits<float>::infinity();
        uint16_t bits = atb_llm::Fp32ToFp16(ninf);
        float    back = atb_llm::Fp16ToF32(bits);
        bool ok = (bits == 0xfbff) && std::isfinite(back) && back < 0.0f;
        LOG_INFO("  [%s] -inf → 0x%04x → %.3g (CANN saturates to min-finite)",
                 ok ? "PASS" : "FAIL", bits, back);
        if (!ok) all_ok = false;
    }

    // NaN → CANN collapses to 0x7bff (max-finite). Document this.
    {
        float nan = std::numeric_limits<float>::quiet_NaN();
        uint16_t bits = atb_llm::Fp32ToFp16(nan);
        bool ok = (bits == 0x7bff);
        LOG_INFO("  [%s] NaN  → 0x%04x (CANN collapses NaN to max-finite)",
                 ok ? "PASS" : "FAIL", bits);
        if (!ok) all_ok = false;
    }

    // Bf16 NaN → propagated through Fp32ToFp16, so also collapses to 0x7bff.
    {
        // bf16 NaN: exponent all-ones (0xFF), any non-zero mantissa (7 bits).
        // 0x7FC1 = sign 0, exp 0xFF, mantissa 0x41 (non-zero) → bf16 quiet NaN
        uint16_t bf16_nan = 0x7FC1;
        uint16_t fp16     = atb_llm::Bf16ToFp16(bf16_nan);
        bool ok = (fp16 == 0x7bff);
        LOG_INFO("  [%s] bf16 NaN (0x%04x) → fp16 0x%04x (CANN collapses NaN)",
                 ok ? "PASS" : "FAIL", bf16_nan, fp16);
        if (!ok) all_ok = false;
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 5: FloatToUint32 byte-level correctness
// ═══════════════════════════════════════════════════════════════
static bool TestFloatToUint32() {
    LOG_INFO("\n=== Test 5: FloatToUint32 type-pun byte equivalence ===");

    struct Case {
        const char* name;
        float value;
        uint32_t expected_bits;  // IEEE-754 single
    };
    const Case cases[] = {
        {"zero",      0.0f,                                  0x00000000u},
        {"neg zero", -0.0f,                                  0x80000000u},
        {"one",       1.0f,                                  0x3F800000u},
        {"neg one",  -1.0f,                                  0xBF800000u},
        {"two",       2.0f,                                  0x40000000u},
        {"half",      0.5f,                                  0x3F000000u},
        {"+inf",      std::numeric_limits<float>::infinity(),0x7F800000u},
        {"-inf",     -std::numeric_limits<float>::infinity(),0xFF800000u},
    };

    bool all_ok = true;
    for (const auto& c : cases) {
        uint32_t bits = atb_llm::FloatToUint32(c.value);

        // Verify byte-level equivalence with memcpy ground truth.
        uint32_t reference;
        std::memcpy(&reference, &c.value, sizeof(reference));

        bool ok = (bits == c.expected_bits) && (bits == reference);
        if (ok) {
            LOG_INFO("  [PASS] %s: %g → 0x%08x", c.name, c.value, bits);
        } else {
            LOG_ERROR("  [FAIL] %s: %g → 0x%08x (expected 0x%08x, memcpy=0x%08x)",
                      c.name, c.value, bits, c.expected_bits, reference);
            all_ok = false;
        }
    }

    // Round-trip random-ish values
    {
        const float roundtrip_values[] = {3.14159265f, -2.71828f, 1.0e-10f, 1.0e10f};
        bool rt_ok = true;
        for (float v : roundtrip_values) {
            uint32_t bits = atb_llm::FloatToUint32(v);
            float restored;
            std::memcpy(&restored, &bits, sizeof(restored));
            bool eq = (std::memcmp(&restored, &v, sizeof(float)) == 0);
            if (!eq) {
                LOG_ERROR("  [FAIL] roundtrip %g → 0x%08x → %g (bit mismatch)", v, bits, restored);
                rt_ok = false;
            }
        }
        if (rt_ok) {
            LOG_INFO("  [PASS] Bit-exact round-trip for all sample values");
        } else {
            all_ok = false;
        }
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== Float Utils CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++; if (TestFp32Fp16Roundtrip())         passed++;
    total++; if (TestBf16ToFp16AgainstPython())   passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage float_utils' first");
    total++; if (TestBf16ToFp16Buffer())          passed++;
    total++; if (TestSpecialValues())             passed++;
    total++; if (TestFloatToUint32())             passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
