/**
 * Level 1 CPU pure-function tests: SmartResize and related preprocessing functions.
 *
 * NO NPU required — CPU-only computations.
 * Compares against Python reference data generated by gen_cpu_reference.py.
 *
 * Prerequisites:
 *     python tests/gen_cpu_reference.py --stage smart_resize
 *
 * Run: ./test_preprocess_cpu
 */

#include "adapters/qwen3vl_embedding/qwen3vl_preprocess.h"
#include "adapters/qwen3vl_embedding/qwen3vl_config.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>

namespace {

// ── Load SmartResize reference data ────────────────────────
// Format: [count: int64] [data: int32[count]]  (in_h, in_w, out_h, out_w) pairs
struct SmartResizeRef {
    struct Case {
        int32_t in_h, in_w, out_h, out_w;
    };
    std::vector<Case> cases;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t count;
        if (fread(&count, sizeof(int64_t), 1, f) != 1) {
            fclose(f);
            return false;
        }
        std::vector<int32_t> data(count);
        if (fread(data.data(), sizeof(int32_t), count, f) != static_cast<size_t>(count)) {
            fclose(f);
            return false;
        }
        fclose(f);

        for (int64_t i = 0; i + 3 < count; i += 4) {
            cases.push_back({data[i], data[i+1], data[i+2], data[i+3]});
        }
        return true;
    }
};

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: SmartResize against Python reference
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeAgainstPython() {
    LOG_INFO("=== Test 1: SmartResize against Python reference ===");

    SmartResizeRef ref;
    if (!ref.Load("/tmp/cpu_smart_resize.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_smart_resize.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage smart_resize");
        return false;
    }

    int32_t factor = 32;
    int32_t min_px = 4096;
    int32_t max_px = 1310720;

    bool all_ok = true;
    for (size_t i = 0; i < ref.cases.size(); i++) {
        auto& c = ref.cases[i];
        int32_t nh = 0, nw = 0;
        atb_llm::adapters::SmartResize(c.in_h, c.in_w, factor, min_px, max_px, nh, nw);

        bool ok = (nh == c.out_h && nw == c.out_w);
        if (ok) {
            LOG_INFO("  [PASS] case %zu: (%d,%d) -> (%d,%d) = Python (%d,%d)",
                     i, c.in_h, c.in_w, nh, nw, c.out_h, c.out_w);
        } else {
            LOG_ERROR("  [FAIL] case %zu: (%d,%d) -> C++(%d,%d) != Python(%d,%d)",
                     i, c.in_h, c.in_w, nh, nw, c.out_h, c.out_w);
            all_ok = false;
        }
    }
    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: SmartResize — banker's rounding (regression)
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeBankers() {
    LOG_INFO("\n=== Test 2: SmartResize — banker's rounding regression ===");

    // The key regression case: 720 / 32 = 22.5
    // Standard rounding: round(22.5) = 23 → 23*32 = 736
    // Banker's rounding: round(22.5) = 22 (even!) → 22*32 = 704
    // Python uses banker's rounding → 704
    int32_t h = 720, w = 1000;
    int32_t factor = 32, min_px = 4096, max_px = 1280 * 720 * 4;
    int32_t nh = 0, nw = 0;

    atb_llm::adapters::SmartResize(h, w, factor, min_px, max_px, nh, nw);

    // With banker's rounding: 720/32=22.5→22, 1000/32=31.25→31, so 704x992
    // With standard rounding: 720/32=22.5→23, so 736x992
    // The expected (from Python): 704x992
    int32_t expected_h = 704, expected_w = 992;

    bool ok = (nh == expected_h && nw == expected_w);
    if (ok) {
        LOG_INFO("  [PASS] 720x1000 -> %dx%d (banker's rounding correct)", nh, nw);
    } else {
        LOG_ERROR("  [FAIL] 720x1000 -> %dx%d (expected %dx%d with banker's rounding)",
                 nh, nw, expected_h, expected_w);
    }
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: SmartResize — boundary conditions
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeBoundary() {
    LOG_INFO("\n=== Test 3: SmartResize — boundary conditions ===");

    int32_t factor = 32, min_px = 4096, max_px = 1310720;
    int32_t nh = 0, nw = 0;

    // Case A: very small image (below min_pixels)
    {
        atb_llm::adapters::SmartResize(4, 4, factor, min_px, max_px, nh, nw);
        LOG_INFO("  [INFO] (4,4) → (%d,%d) — upscaled to meet min_pixels=%d",
                 nh, nw, min_px);
        int64_t area = static_cast<int64_t>(nh) * nw;
        bool ok = (area >= min_px);
        LOG_INFO("  [%s] Pixel area %ld ≥ min %d", ok ? "PASS" : "FAIL", area, min_px);
    }

    // Case B: very large image (above max_pixels)
    {
        atb_llm::adapters::SmartResize(3000, 4000, factor, min_px, max_px, nh, nw);
        LOG_INFO("  [INFO] (3000,4000) → (%d,%d) — downscaled to meet max_pixels=%d",
                 nh, nw, max_px);
        int64_t area = static_cast<int64_t>(nh) * nw;
        bool ok = (area <= max_px);
        LOG_INFO("  [%s] Pixel area %ld ≤ max %d", ok ? "PASS" : "FAIL", area, max_px);
    }

    // Case C: already divisible by factor
    {
        atb_llm::adapters::SmartResize(128, 256, factor, min_px, max_px, nh, nw);
        bool ok = (nh == 128 && nw == 256);
        LOG_INFO("  [%s] (128,256) → (%d,%d)", ok ? "PASS" : "FAIL", nh, nw);
    }

    return true;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== Preprocess CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++;
    if (TestSmartResizeAgainstPython()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage smart_resize' first");

    total++;
    if (TestSmartResizeBankers()) passed++;

    total++;
    if (TestSmartResizeBoundary()) passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
