/**
 * Level 1 CPU pure-function tests: VisionRotaryEmbedding and ComputeVisionRotPosEmb.
 *
 * NO NPU required — these functions are pure CPU computation.
 * Compares against Python reference data generated by gen_cpu_reference.py.
 *
 * Prerequisites:
 *     python tests/gen_cpu_reference.py --stage vision_rope
 *
 * Run: ./test_vision_rope_cpu
 */

#include "components/common/mrope.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>

namespace {

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) return false;
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) return false;
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(float), total, f) != static_cast<size_t>(total)) return false;
        fclose(f);
        return true;
    }
};

float CosineSim(const float* a, const float* b, int64_t n) {
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na += static_cast<double>(a[i]) * a[i];
        nb += static_cast<double>(b[i]) * b[i];
    }
    return static_cast<float>(dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12));
}

float MaxAbsDiff(const float* a, const float* b, int64_t n) {
    float max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = std::fabs(a[i] - b[i]);
        if (d > max_d) max_d = d;
    }
    return max_d;
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: VisionRotaryEmbedding — frequency table
// ═══════════════════════════════════════════════════════════════
static bool TestFreqTable() {
    LOG_INFO("=== Test 1: VisionRotaryEmbedding::ComputeFreqTable ===");

    LoadedArrayF32 ref;
    if (!ref.Load("/tmp/cpu_vision_freq_table.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_vision_freq_table.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage vision_rope");
        return false;
    }

    // Python: vis_rope = VisionRotaryEmbedding(dim=32) for head_dim//2
    int32_t dim = 32;
    atb_llm::components::VisionRotaryEmbedding rotary(dim);

    // Python used max_hw = 6 (from grid [1,4,6])
    int32_t max_hw = 6;
    auto freq_table = rotary.ComputeFreqTable(max_hw);
    // freq_table shape: (max_hw, dim) = (6, 32) row-major

    int64_t n = static_cast<int64_t>(freq_table.size());
    int64_t ref_n = static_cast<int64_t>(ref.data.size());
    int64_t cmp_n = std::min(n, ref_n);

    float cos = CosineSim(freq_table.data(), ref.data.data(), cmp_n);
    float max_d = MaxAbsDiff(freq_table.data(), ref.data.data(), cmp_n);

    LOG_INFO("  C++ freq_table: (%d, %d) elements=%zu  Ref shape: (%ld, %ld) total=%ld",
             max_hw, dim, freq_table.size(), ref.shape[0], ref.shape[1], ref.data.size());
    LOG_INFO("  Cosine: %.6f  MaxDiff: %.8f", cos, max_d);

    bool pass = (cos > 0.9999f);
    if (pass) {
        LOG_INFO("  [PASS] Freq table matches Python reference");
    } else {
        LOG_ERROR("  [FAIL] Freq table diverges");
        // Show first mismatches
        int shown = 0;
        for (int64_t i = 0; i < cmp_n && shown < 5; i++) {
            float d = std::fabs(freq_table[i] - ref.data[i]);
            if (d > 1e-6f) {
                LOG_ERROR("    [%ld] C++=%.8f Python=%.8f diff=%.8f",
                         i, freq_table[i], ref.data[i], d);
                shown++;
            }
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: ComputeVisionRotPosEmb — cos/sin for grid [1, 4, 6]
// ═══════════════════════════════════════════════════════════════
static bool TestVisionRoPECosSin() {
    LOG_INFO("\n=== Test 2: ComputeVisionRotPosEmb — cos/sin ===");

    LoadedArrayF32 ref_cos, ref_sin;
    if (!ref_cos.Load("/tmp/cpu_vision_rope_cos.bin") ||
        !ref_sin.Load("/tmp/cpu_vision_rope_sin.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_vision_rope_cos.bin or sin.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage vision_rope");
        return false;
    }

    // Python: grid [1,4,6], merge=2, max_hw=max(4,6)=6
    int32_t dim = 32;  // VisionRotaryEmbedding dim (= head_dim//2)
    atb_llm::components::VisionRotaryEmbedding rotary(dim);

    int64_t grid_thw[] = {1, 4, 6};
    int64_t num_images = 1;
    int32_t merge_size = 2;
    int32_t max_hw = 6;

    auto freq_table = rotary.ComputeFreqTable(max_hw);

    // Total tokens: 1 * 4 * 6 = 24
    // Output per token: dim*2 = 64 (this matches Python: emb = Concat(rope, rope))
    // Actually Python returns cos/sin of emb which is Concat(rope, rope) where rope has dim*2
    // So output is dim*4 per token? Let me re-read the code.
    //
    // In ComputeVisionRotPosEmb (C++):
    //   out_dim = half * 4 = dim * 2  (since half = dim/2)
    //   Each token gets: row_freq[half] + col_freq[half] + (row+col)[half] repeat
    //   = half*4 elements
    //
    // In Python compute_rot_pos_emb:
    //   rope = freq_table[pos_ids].flatten(1) → (total_tokens, dim*2)  (row+col)
    //   emb = Concat(rope, rope) → (total_tokens, dim*4)
    //   cos = emb.cos(), sin = emb.sin()
    //
    // Wait, the Python code says:
    //   rope = compute_rot_pos_emb(grid_thw, vis_rope, merge_size)
    //   emb = torch.cat((rope, rope), dim=-1)
    //   cos = emb.cos()
    //
    // So rope has shape (total_tokens, dim*2) = (24, 64)
    // emb has shape (24, 128)
    // cos/sin have shape (24, 128)
    //
    // C++ ComputeVisionRotPosEmb outputs: out_dim = half*4 = dim*2 per token
    // half = dim/2 = 16, so out_dim = 64 per token
    // Wait, that's only 64, not 128. Let me re-read the C++ code.

    int64_t total_tokens = 1 * 4 * 6;  // 24
    int32_t half = dim / 2;  // 16
    int32_t out_dim = half * 4;  // 64

    std::vector<float> cos_out(total_tokens * out_dim);
    std::vector<float> sin_out(total_tokens * out_dim);

    int64_t num = atb_llm::components::ComputeVisionRotPosEmb(
        grid_thw, num_images, rotary, merge_size,
        freq_table, cos_out.data(), sin_out.data());

    LOG_INFO("  Total tokens: %ld (expected %ld)", num, total_tokens);
    LOG_INFO("  Output per token: %d elements", out_dim);
    LOG_INFO("  C++ cos shape: (%ld, %d)", num, out_dim);
    LOG_INFO("  Python ref cos shape: (%ld, %ld)", ref_cos.shape[0], ref_cos.shape[1]);

    // The C++ output is (total_tokens, out_dim) where out_dim = half*4 = dim*2
    // The Python ref is (total_tokens, dim*4) because emb = Concat(rope, rope) -> double again
    // So Python ref has 2x the columns of C++ ComputeVisionRotPosEmb.
    //
    // Compare the first out_dim elements per token: C++ vs first half of Python
    // Actually, C++ ComputeVisionRotPosEmb already doubles the row+col: see code
    // std::memcpy(cos_row + half*2, cos_row, half*2 * sizeof(float));
    // This makes cos_row = [row_freq_cos, col_freq_cos, row_freq_cos_dup, col_freq_cos_dup]
    // So length = half*2 + half*2 = half*4 = dim*2 = 64
    // Python emb = Concat(rope, rope) where rope = [row_freq, col_freq] (half*2 = 32, doubled = 64)
    // wait, row_freq has 'half' elements (16), col_freq has 'half' elements (16), concatenated = 32
    // rope = Concat(row_freq, col_freq) = 32 elements
    // emb = Concat(rope, rope) = 64 elements
    // cos = emb.cos() → 64 elements per token
    //
    // So C++ out_dim = 64 and Python ref = 64. They should match!

    float cos_cs = CosineSim(cos_out.data(), ref_cos.data.data(),
                             static_cast<int64_t>(cos_out.size()));
    float sin_cs = CosineSim(sin_out.data(), ref_sin.data.data(),
                             static_cast<int64_t>(sin_out.size()));
    float cos_maxd = MaxAbsDiff(cos_out.data(), ref_cos.data.data(),
                                static_cast<int64_t>(cos_out.size()));
    float sin_maxd = MaxAbsDiff(sin_out.data(), ref_sin.data.data(),
                                static_cast<int64_t>(sin_out.size()));

    LOG_INFO("  Cosine: cos=%.6f  sin=%.6f", cos_cs, sin_cs);
    LOG_INFO("  MaxDiff: cos=%.8f  sin=%.8f", cos_maxd, sin_maxd);

    bool pass = (cos_cs > 0.9999f) && (sin_cs > 0.9999f);
    if (pass) {
        LOG_INFO("  [PASS] Vision RoPE cos/sin match Python reference");
    } else {
        LOG_ERROR("  [FAIL] Vision RoPE cos/sin diverge");
        // Show first few values
        LOG_INFO("  C++ cos first 8: %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f",
                 cos_out[0], cos_out[1], cos_out[2], cos_out[3],
                 cos_out[4], cos_out[5], cos_out[6], cos_out[7]);
        LOG_INFO("  Ref cos first 8: %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f",
                 ref_cos.data[0], ref_cos.data[1], ref_cos.data[2], ref_cos.data[3],
                 ref_cos.data[4], ref_cos.data[5], ref_cos.data[6], ref_cos.data[7]);
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: ComputeVisionRotPosEmb — multi-image case
// ═══════════════════════════════════════════════════════════════
static bool TestVisionRoPEMultiImage() {
    LOG_INFO("\n=== Test 3: ComputeVisionRotPosEmb — multi-image ===");

    int32_t dim = 32;
    atb_llm::components::VisionRotaryEmbedding rotary(dim);

    // Two small images
    int64_t grid_thw[] = {1, 4, 4, 1, 6, 6};
    int64_t num_images = 2;
    int32_t merge_size = 2;
    int32_t max_hw = 6;

    auto freq_table = rotary.ComputeFreqTable(max_hw);

    // Total tokens: 4*4 + 6*6 = 16 + 36 = 52
    int64_t expected_tokens = 16 + 36;
    int32_t half = dim / 2;
    int32_t out_dim = half * 4;  // 64

    std::vector<float> cos_out(expected_tokens * out_dim);
    std::vector<float> sin_out(expected_tokens * out_dim);

    int64_t num = atb_llm::components::ComputeVisionRotPosEmb(
        grid_thw, num_images, rotary, merge_size,
        freq_table, cos_out.data(), sin_out.data());

    LOG_INFO("  Total tokens: %ld (expected %ld)", num, expected_tokens);

    // Verify all cos/sin values are in [-1, 1]
    bool valid = true;
    for (int64_t i = 0; i < num * out_dim; i++) {
        if (cos_out[i] < -1.0f || cos_out[i] > 1.0f) {
            valid = false;
            break;
        }
        if (sin_out[i] < -1.0f || sin_out[i] > 1.0f) {
            valid = false;
            break;
        }
    }

    if (num == expected_tokens && valid) {
        LOG_INFO("  [PASS] Multi-image RoPE: correct token count, values in range");
        return true;
    } else {
        LOG_ERROR("  [FAIL] token_count=%ld (expected %ld), valid=%d",
                 num, expected_tokens, valid);
        return false;
    }
}

// ═══════════════════════════════════════════════════════════════
// Test 4: VisionRotaryEmbedding — empty grid
// ═══════════════════════════════════════════════════════════════
static bool TestVisionRoPEEdgeCases() {
    LOG_INFO("\n=== Test 4: VisionRotaryEmbedding — edge cases ===");

    int32_t dim = 32;
    atb_llm::components::VisionRotaryEmbedding rotary(dim);

    // Case A: freq table for max_hw=1 (should have 1 * dim/2 elements)
    {
        auto ft = rotary.ComputeFreqTable(1);
        int32_t expected_cols = dim / 2;
        bool ok = (static_cast<int32_t>(ft.size()) == 1 * expected_cols);
        LOG_INFO("  [%s] max_hw=1: %zu elements (expected %d)",
                 ok ? "PASS" : "FAIL", ft.size(), expected_cols);
    }

    // Case B: single token (grid [1, 1, 1], merge=1)
    {
        int64_t grid_thw[] = {1, 1, 1};
        auto ft = rotary.ComputeFreqTable(1);
        int32_t half = dim / 2;
        int32_t out_dim = half * 4;
        std::vector<float> cos_out(1 * out_dim), sin_out(1 * out_dim);
        int64_t num = atb_llm::components::ComputeVisionRotPosEmb(
            grid_thw, 1, rotary, 1, ft, cos_out.data(), sin_out.data());
        bool ok = (num == 1);
        LOG_INFO("  [%s] single token: num=%ld, cos[0]=%.6f sin[0]=%.6f",
                 ok ? "PASS" : "FAIL", num, cos_out[0], sin_out[0]);
    }

    return true;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== Vision Rotary Embedding CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++;
    if (TestFreqTable()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage vision_rope' first");

    total++;
    if (TestVisionRoPECosSin()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage vision_rope' first");

    total++;
    if (TestVisionRoPEMultiImage()) passed++;

    total++;
    if (TestVisionRoPEEdgeCases()) passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
