/**
 * Level 1 CPU pure-function tests: GetRopeIndex and MRoPE::Compute.
 *
 * NO NPU required — these functions are pure CPU computation.
 * Compares against Python reference data generated by gen_cpu_reference.py.
 *
 * Prerequisites:
 *     1. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_simple
 *     2. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_no_img
 *     3. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_image_text
 *     4. python tests/python_reference/gen_cpu_reference.py --stage mrope_cos_sin
 *     5. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_multi_img
 *     6. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_chat_template
 *     7. python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_boundary
 *
 * Run: ./test_mrope_cpu
 */

#include "components/common/mrope.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>

namespace {

// ── Binary file loader ──────────────────────────────────────
// Format: [ndim: int64] [shape: int64[ndim]] [data: raw]

struct LoadedArrayI64 {
    std::vector<int64_t> shape;
    std::vector<int64_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        fread(&ndim, sizeof(int64_t), 1, f);
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            fread(&shape[i], sizeof(int64_t), 1, f);
            total *= shape[i];
        }
        data.resize(total);
        fread(data.data(), sizeof(int64_t), total, f);
        fclose(f);
        return true;
    }
};

struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        fread(&ndim, sizeof(int64_t), 1, f);
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            fread(&shape[i], sizeof(int64_t), 1, f);
            total *= shape[i];
        }
        data.resize(total);
        fread(data.data(), sizeof(float), total, f);
        fclose(f);
        return true;
    }
};

// ── Cosine similarity ──────────────────────────────────────
float CosineSim(const float* a, const float* b, int64_t n) {
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na += static_cast<double>(a[i]) * a[i];
        nb += static_cast<double>(b[i]) * b[i];
    }
    return static_cast<float>(dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12));
}

// ── Print int64 array ──────────────────────────────────────
void PrintI64(const int64_t* data, int64_t n, const char* label) {
    std::string s;
    s += label;
    s += " [";
    for (int64_t i = 0; i < n && i < 20; i++) {
        s += std::to_string(data[i]);
        if (i + 1 < n) s += ", ";
    }
    if (n > 20) s += "...";
    s += "]";
    LOG_INFO("%s", s.c_str());
}

// ── Count mismatches ───────────────────────────────────────
int64_t CountMismatches(const int64_t* a, const int64_t* b, int64_t n) {
    int64_t c = 0;
    for (int64_t i = 0; i < n; i++) {
        if (a[i] != b[i]) c++;
    }
    return c;
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: GetRopeIndex — image-only (vision_start + image tokens)
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexSimple() {
    LOG_INFO("=== Test 1: GetRopeIndex — image-only case ===");

    LoadedArrayI64 ref;
    if (!ref.Load("/tmp/cpu_mrope_pid_simple.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_mrope_pid_simple.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage mrope_pid_simple");
        return false;
    }

    // Input: [vision_start, img, img, img, img]
    int64_t input_ids[] = {151652, 151655, 151655, 151655, 151655};
    int64_t grid_thw[] = {1, 4, 4};
    int64_t B = 1, S = 5, N = 1;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, grid_thw, N,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    LOG_INFO("  C++ position_ids:");
    for (int d = 0; d < 3; d++) {
        PrintI64(pid_out.data() + d * B * S, S,
                 (std::string("    dim ") + std::to_string(d)).c_str());
    }

    LOG_INFO("  Python reference:");
    for (int d = 0; d < 3; d++) {
        PrintI64(ref.data.data() + d * B * S, S,
                 (std::string("    dim ") + std::to_string(d)).c_str());
    }

    // Compare: ref shape is (3, B, S)
    int64_t ref_total = ref.data.size();
    int64_t cpp_total = static_cast<int64_t>(pid_out.size());
    int64_t n = std::min(ref_total, cpp_total);

    // ref layout: (3, B, S), C++ layout: (3, B, S) — both contiguous row-major
    int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Exact match (all %ld elements identical)", n);
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches out of %ld elements", mismatches, n);
        // Show first 5 mismatches
        int shown = 0;
        for (int64_t i = 0; i < n && shown < 5; i++) {
            if (pid_out[i] != ref.data[i]) {
                int64_t d = static_cast<int64_t>(i) / (B * S);
                int64_t b = (i % (B * S)) / S;
                int64_t s = i % S;
                LOG_ERROR("    dim=%ld batch=%ld seq=%ld: C++=%ld Python=%ld",
                         d, b, s, pid_out[i], ref.data[i]);
                shown++;
            }
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: GetRopeIndex — text-only (no images)
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexNoImage() {
    LOG_INFO("\n=== Test 2: GetRopeIndex — text-only case ===");

    LoadedArrayI64 ref;
    if (!ref.Load("/tmp/cpu_mrope_pid_no_img.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_mrope_pid_no_img.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage mrope_pid_no_img");
        return false;
    }

    // Input tokens: [151643, 15339, 1879, 119, 258] (no image tokens)
    int64_t input_ids[] = {151643, 15339, 1879, 119, 258};
    int64_t B = 1, S = 5;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, nullptr, 0,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    // Expected: all dims get sequential positions [0, 1, 2, 3, 4]
    int64_t n = static_cast<int64_t>(pid_out.size());
    int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Exact match (all %ld elements identical)", n);
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches out of %ld elements", mismatches, n);
        for (int d = 0; d < 3; d++) {
            PrintI64(pid_out.data() + d * B * S, S,
                     (std::string("C++ dim ") + std::to_string(d)).c_str());
            PrintI64(ref.data.data() + d * B * S, S,
                     (std::string("Ref dim ") + std::to_string(d)).c_str());
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: GetRopeIndex — text + image + text (mixed)
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexImageText() {
    LOG_INFO("\n=== Test 3: GetRopeIndex — image+text mixed case ===");

    LoadedArrayI64 ref;
    if (!ref.Load("/tmp/cpu_mrope_pid_image_text.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_mrope_pid_image_text.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage mrope_pid_image_text");
        return false;
    }

    // [<|im_start|>, vision_start, img, img, img, img, "the", "image"]
    int64_t input_ids[] = {151643, 151652, 151655, 151655, 151655, 151655, 15339, 1879};
    int64_t grid_thw[] = {1, 4, 4};
    int64_t B = 1, S = 8, N = 1;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, grid_thw, N,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    int64_t n = static_cast<int64_t>(pid_out.size());
    int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Exact match (all %ld elements identical)", n);
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches out of %ld elements", mismatches, n);
        for (int d = 0; d < 3; d++) {
            PrintI64(pid_out.data() + d * B * S, S,
                     (std::string("C++ dim ") + std::to_string(d)).c_str());
            PrintI64(ref.data.data() + d * B * S, S,
                     (std::string("Ref dim ") + std::to_string(d)).c_str());
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 4: GetRopeIndex — regression: IMAGE_ONLY without vision_start
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexImageOnlyNoVisionStart() {
    LOG_INFO("\n=== Test 4: GetRopeIndex — IMAGE_ONLY without vision_start (regression) ===");

    // Reproduce the scenario that caused the IMAGE_ONLY cos=0.844 bug:
    // All tokens are IMAGE_TOKEN_ID, NO vision_start_token_id present.
    // Expected: all tokens get sequential positions [0,1,2,...] like text-only.
    int64_t input_ids[] = {151655, 151655, 151655, 151655, 151655, 151655};
    int64_t grid_thw[] = {1, 3, 2};  // valid grid but no vision_start to pair
    int64_t B = 1, S = 6, N = 1;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, grid_thw, N,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    // Expected: sequential positions for ALL dims [0,1,2,3,4,5]
    int64_t expected[18];
    for (int i = 0; i < 6; i++) {
        expected[i] = i;           // T dim
        expected[6 + i] = i;       // H dim
        expected[12 + i] = i;      // W dim
    }

    int64_t mismatches = CountMismatches(pid_out.data(), expected, 18);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Correctly falls back to sequential positions");
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches — sequential fallback broken!", mismatches);
        for (int d = 0; d < 3; d++) {
            PrintI64(pid_out.data() + d * B * S, S,
                     (std::string("C++ dim ") + std::to_string(d)).c_str());
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 5: GetRopeIndex — empty input (S=0)
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexEdgeCases() {
    LOG_INFO("\n=== Test 5: GetRopeIndex — edge cases ===");
    bool all_ok = true;

    // Case A: B=1, S=1 (single text token)
    {
        int64_t input_ids[] = {151643};
        int64_t B = 1, S = 1;
        std::vector<int64_t> pid_out(3 * B * S);
        atb_llm::components::GetRopeIndex(input_ids, B, S, nullptr, 0,
                                           151655, 151652, 2, pid_out.data());
        // All 3 dims should be [0]
        bool ok = (pid_out[0] == 0 && pid_out[1] == 0 && pid_out[2] == 0);
        all_ok &= ok;
        if (ok) {
            LOG_INFO("  [PASS] Single token: all positions = 0");
        } else {
            LOG_ERROR("  [FAIL] Single token: got [%ld, %ld, %ld], expected [0,0,0]",
                     pid_out[0], pid_out[1], pid_out[2]);
        }
    }

    // Case B: boundary image tokens scenario removed.
    // The expected output for boundary image token cases is difficult to verify
    // by hand (the original author noted this case "may have issues"). This
    // scenario is now covered by the mrope precision E2E test at higher level.

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 6: MRoPE::Compute — cos/sin precision
// ═══════════════════════════════════════════════════════════════
static bool TestMRoPECompute() {
    LOG_INFO("\n=== Test 6: MRoPE::Compute — cos/sin precision ===");

    LoadedArrayI64 ref_pid;
    LoadedArrayF32 ref_cos, ref_sin;
    if (!ref_pid.Load("/tmp/cpu_mrope_pid.bin") ||
        !ref_cos.Load("/tmp/cpu_mrope_cos.bin") ||
        !ref_sin.Load("/tmp/cpu_mrope_sin.bin")) {
        LOG_ERROR("SKIP: reference files not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage mrope_cos_sin");
        return false;
    }

    // Init MRoPE
    int32_t head_dim = 128;
    float rope_theta = 5000000.0f;
    std::vector<int32_t> mrope_section = {24, 20, 20};
    atb_llm::components::MRoPE mrope(head_dim, rope_theta, mrope_section);

    // ref_pid shape: (3, B=1, S=8)
    int64_t B = (ref_pid.shape.size() >= 2) ? ref_pid.shape[1] : 1;
    int64_t S = (ref_pid.shape.size() >= 3) ? ref_pid.shape[2] : ref_pid.shape[1];
    int64_t total_tokens = B * S;

    LOG_INFO("  ref_pid shape: (%ld, %ld, %ld) B=%ld S=%ld",
             ref_pid.shape[0],
             ref_pid.shape.size() > 1 ? ref_pid.shape[1] : 0,
             ref_pid.shape.size() > 2 ? ref_pid.shape[2] : 0,
             B, S);

    // Compute
    std::vector<float> cos_out(total_tokens * head_dim);
    std::vector<float> sin_out(total_tokens * head_dim);
    mrope.Compute(ref_pid.data.data(), B, S, cos_out.data(), sin_out.data());

    // Compare: flatten for cosine (shapes may differ cos_out is (B*S, head_dim), ref is (B, S, head_dim))
    int64_t cos_n = total_tokens * head_dim;
    int64_t ref_cos_n = static_cast<int64_t>(ref_cos.data.size());
    int64_t ref_sin_n = static_cast<int64_t>(ref_sin.data.size());
    float cos_cs = CosineSim(cos_out.data(), ref_cos.data.data(), std::min(cos_n, ref_cos_n));
    float sin_cs = CosineSim(sin_out.data(), ref_sin.data.data(), std::min(cos_n, ref_sin_n));

    LOG_INFO("  Cosine: cos=%.6f  sin=%.6f", cos_cs, sin_cs);

    bool pass = (cos_cs > 0.9999f) && (sin_cs > 0.9999f);
    if (pass) {
        LOG_INFO("  [PASS] MRoPE cos/sin match Python reference (cosine > 0.9999)");
    } else {
        LOG_ERROR("  [FAIL] MRoPE cos/sin diverge");

        // Show first few values
        LOG_INFO("  C++ cos first 10: %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f",
                 cos_out[0], cos_out[1], cos_out[2], cos_out[3], cos_out[4],
                 cos_out[5], cos_out[6], cos_out[7], cos_out[8], cos_out[9]);
        LOG_INFO("  Ref cos first 10: %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f",
                 ref_cos.data[0], ref_cos.data[1], ref_cos.data[2], ref_cos.data[3],
                 ref_cos.data[4], ref_cos.data[5], ref_cos.data[6], ref_cos.data[7],
                 ref_cos.data[8], ref_cos.data[9]);
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 7: GetRopeIndex — multi-image (two images)
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexMultiImage() {
    LOG_INFO("\n=== Test 7: GetRopeIndex — multi-image (two images) ===");

    LoadedArrayI64 ref;
    if (!ref.Load("/tmp/cpu_mrope_pid_multi_img.bin")) {
        LOG_ERROR("SKIP: reference not found");
        LOG_ERROR("  Run: python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_multi_img");
        return false;
    }

    // Two images with independent grid positions:
    //   Image 1: 2x2 grid → 1x1 merged = 1 image token
    //   Image 2: 4x4 grid → 2x2 merged = 4 image tokens
    // Sequence: [VS, IMG, "the", VS, IMG, IMG, IMG, IMG, "image"]
    int64_t input_ids[] = {151652, 151655, 15339,
                           151652, 151655, 151655, 151655, 151655,
                           1879};
    int64_t grid_thw[] = {1, 2, 2,      // image 1: t=1, h=2, w=2
                           1, 4, 4};     // image 2: t=1, h=4, w=4
    int64_t B = 1, S = 9, N = 2;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, grid_thw, N,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    LOG_INFO("  C++ position_ids:");
    for (int d = 0; d < 3; d++) {
        PrintI64(pid_out.data() + d * B * S, S,
                 (std::string("    dim ") + std::to_string(d)).c_str());
    }

    LOG_INFO("  Python reference:");
    for (int d = 0; d < 3; d++) {
        PrintI64(ref.data.data() + d * B * S, S,
                 (std::string("    dim ") + std::to_string(d)).c_str());
    }

    int64_t n = std::min(static_cast<int64_t>(pid_out.size()),
                         static_cast<int64_t>(ref.data.size()));
    int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Byte-exact match — each image gets independent grid positions");
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches out of %ld elements", mismatches, n);
        // Show first mismatches with per-dimension context
        int shown = 0;
        for (int64_t i = 0; i < n && shown < 8; i++) {
            if (pid_out[i] != ref.data[i]) {
                int64_t d = static_cast<int64_t>(i) / (B * S);
                int64_t b = (i % (B * S)) / S;
                int64_t s = i % S;
                LOG_ERROR("    dim=%ld batch=%ld seq=%ld: C++=%ld Python=%ld",
                         d, b, s, pid_out[i], ref.data[i]);
                shown++;
            }
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 8: GetRopeIndex — chat template tokens
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexChatTemplate() {
    LOG_INFO("\n=== Test 8: GetRopeIndex — chat template tokens ===");

    LoadedArrayI64 ref;
    if (!ref.Load("/tmp/cpu_mrope_pid_chat_template.bin")) {
        LOG_ERROR("SKIP: reference not found");
        LOG_ERROR("  Run: python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_chat_template");
        return false;
    }

    // Representative chat template sequence:
    // [<|im_start|>, <|im_start|>, <|vision_start|>, <|image_pad|>x4, "the", "image", <|im_end|>]
    // This mirrors the ACTUAL Qwen3VLEmbedder pipeline: system prompt → user role → vision → text.
    int64_t input_ids[] = {
        151643,                      // <|im_start|>
        151643,                      // <|im_start|> (system→user transition)
        151652,                      // <|vision_start|>
        151655, 151655, 151655, 151655, // <|image_pad|> x4 (grid 4x4 → 2x2 merged)
        15339, 1879,                 // "the" "image"
        151645,                      // <|im_end|>
    };
    int64_t grid_thw[] = {1, 4, 4};  // one image, 4x4 grid → 2x2 merged = 4 tokens
    int64_t B = 1, S = 10, N = 1;
    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    std::vector<int64_t> pid_out(3 * B * S);

    atb_llm::components::GetRopeIndex(
        input_ids, B, S, grid_thw, N,
        IMG_TOK, VIS_START, MERGE, pid_out.data());

    int64_t n = std::min(static_cast<int64_t>(pid_out.size()),
                         static_cast<int64_t>(ref.data.size()));
    int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
    bool pass = (mismatches == 0);

    if (pass) {
        LOG_INFO("  [PASS] Byte-exact match for chat template token sequence");
    } else {
        LOG_ERROR("  [FAIL] %ld mismatches out of %ld elements", mismatches, n);
        for (int d = 0; d < 3; d++) {
            PrintI64(pid_out.data() + d * B * S, S,
                     (std::string("C++ dim ") + std::to_string(d)).c_str());
            PrintI64(ref.data.data() + d * B * S, S,
                     (std::string("Ref dim ") + std::to_string(d)).c_str());
        }
    }
    return pass;
}

// ═══════════════════════════════════════════════════════════════
// Test 9: GetRopeIndex — boundary cases for vision_start
// ═══════════════════════════════════════════════════════════════
static bool TestGetRopeIndexVisionStartBoundary() {
    LOG_INFO("\n=== Test 9: GetRopeIndex — vision_start boundary cases ===");
    bool all_ok = true;

    int64_t IMG_TOK = 151655, VIS_START = 151652, MERGE = 2;

    // Helper: run GetRopeIndex on single-batch input and verify against expected.
    auto VerifyCase = [&](const char* label,
                          const int64_t* input_ids, int64_t S,
                          const int64_t* grid_thw, int64_t N,
                          const int64_t* expected) -> bool {
        int64_t B = 1;
        std::vector<int64_t> pid_out(3 * B * S);
        atb_llm::components::GetRopeIndex(
            input_ids, B, S, grid_thw, N,
            IMG_TOK, VIS_START, MERGE, pid_out.data());

        int64_t total = 3 * B * S;
        int64_t mismatches = CountMismatches(pid_out.data(), expected, total);
        if (mismatches == 0) {
            LOG_INFO("  [PASS] %s", label);
            return true;
        } else {
            LOG_ERROR("  [FAIL] %s — %ld mismatches", label, mismatches);
            for (int d = 0; d < 3; d++) {
                PrintI64(pid_out.data() + d * B * S, S,
                         (std::string("    C++ dim ") + std::to_string(d)).c_str());
                PrintI64(expected + d * B * S, S,
                         (std::string("    Exp dim ") + std::to_string(d)).c_str());
            }
            return false;
        }
    };

    // ── Case A: vision_start at position 0 ─────────────────────
    // [VS, IMG, IMG, TXT] with grid [[1,2,2]] → 1 merged token.
    // First IMG gets grid position [1,1,1]; second IMG becomes trailing text.
    {
        int64_t input_ids[] = {151652, 151655, 151655, 151643};
        int64_t grid_thw[] = {1, 2, 2};
        int64_t expected[12] = {
            0, 1, 2, 3,   // dim 0 (T): sequential + grid offset
            0, 1, 2, 3,   // dim 1 (H): same (h=1 after merge)
            0, 1, 2, 3,   // dim 2 (W): same (w=1 after merge)
        };
        all_ok &= VerifyCase("Case A: vision_start at position 0",
                             input_ids, 4, grid_thw, 1, expected);
    }

    // ── Case B: vision_start at S-2, image at S-1 ──────────────
    // [TXT, TXT, VS, IMG] with grid [[1,2,2]] → 1 merged at tail.
    {
        int64_t input_ids[] = {151643, 151643, 151652, 151655};
        int64_t grid_thw[] = {1, 2, 2};
        int64_t expected[12] = {
            0, 1, 2, 3,
            0, 1, 2, 3,
            0, 1, 2, 3,
        };
        all_ok &= VerifyCase("Case B: vision_start at S-2 (image at tail)",
                             input_ids, 4, grid_thw, 1, expected);
    }

    // ── Case C: vision_start at last position (no image after) ─
    // [TXT, TXT, VS] — degenerate: vision_start with no image token.
    // image_nums = 0, all positions sequential.
    {
        int64_t input_ids[] = {151643, 151643, 151652};
        int64_t grid_thw[] = {1, 2, 2};
        int64_t expected[9] = {
            0, 1, 2,
            0, 1, 2,
            0, 1, 2,
        };
        all_ok &= VerifyCase("Case C: vision_start at last position (no image after)",
                             input_ids, 3, grid_thw, 1, expected);
    }

    // ── Case D: two adjacent vision_start tokens ───────────────
    // [VS, VS, IMG, TXT] — first VS has VS after it (not IMG), second VS
    // pairs with IMG. Should NOT crash and should detect exactly 1 image.
    {
        int64_t input_ids[] = {151652, 151652, 151655, 151643};
        int64_t grid_thw[] = {1, 2, 2};
        // first VS+VS pair: vision_start→vision_start, NOT image → not counted
        // second VS+IMG pair: counted → image_nums = 1
        // Text at pos 0,1: [0,1]; Image grid at pos 2: [2,2,2]; Remaining pos 3: [3,3,3]
        int64_t expected[12] = {
            0, 1, 2, 3,
            0, 1, 2, 3,
            0, 1, 2, 3,
        };
        all_ok &= VerifyCase("Case D: adjacent vision_start tokens (no crash)",
                             input_ids, 4, grid_thw, 1, expected);
    }

    // ── Case E: vision_start followed by non-image token ──────
    // [TXT, VS, TXT, IMG] — VS+151643 is NOT a valid image pair.
    // image_nums = 0, so ALL positions must be sequential.
    // This is the REGRESSION test: without vision_start checking,
    // IMG at position 3 would get grid positions rather than sequential.
    {
        int64_t input_ids[] = {151643, 151652, 151643, 151655};
        int64_t grid_thw[] = {1, 2, 2};
        int64_t expected[12] = {
            0, 1, 2, 3,
            0, 1, 2, 3,
            0, 1, 2, 3,
        };
        all_ok &= VerifyCase("Case E: vision_start + non-image (sequential fallback)",
                             input_ids, 4, grid_thw, 1, expected);
    }

    // ── Bonus case: batched boundary ref from Python generator ─
    // The Python gen_cpu_reference.py stage "mrope_pid_boundary" generates
    // reference data for 2 batches with boundary scenarios:
    //   Batch 0: [VS, IMG, IMG, TXT] — vision_start at position 0
    //   Batch 1: [TXT, TXT, VS, IMG] — vision_start at tail
    // Each batch has exactly 1 valid image, so N=2 (one grid per batch).
    LoadedArrayI64 ref;
    if (ref.Load("/tmp/cpu_mrope_pid_boundary.bin")) {
        // ref shape: (3, B=2, S=4) → 3 dims × 2 batches × 4 seq
        int64_t B = 2, S = 4;
        int64_t N = 2;
        int64_t input_ids_all[] = {
            // Batch 0: vision_start at position 0: [VS, IMG, IMG, TXT]
            151652, 151655, 151655, 151643,
            // Batch 1: vision_start + image at tail: [TXT, TXT, VS, IMG]
            151643, 151643, 151652, 151655,
        };
        int64_t grid_thw[] = {1, 2, 2,   // grid for batch 0
                              1, 2, 2};  // grid for batch 1

        std::vector<int64_t> pid_out(3 * B * S);
        atb_llm::components::GetRopeIndex(
            input_ids_all, B, S, grid_thw, N,
            IMG_TOK, VIS_START, MERGE, pid_out.data());

        int64_t n = std::min(static_cast<int64_t>(pid_out.size()),
                             static_cast<int64_t>(ref.data.size()));
        int64_t mismatches = CountMismatches(pid_out.data(), ref.data.data(), n);
        bool bonus_ok = (mismatches == 0);
        if (bonus_ok) {
            LOG_INFO("  [PASS] Batched boundary reference (2 batches, byte-exact)");
        } else {
            LOG_ERROR("  [FAIL] Batched boundary: %ld mismatches", mismatches);
        }
        all_ok &= bonus_ok;
    } else {
        LOG_INFO("  [SKIP] Batched boundary reference not found");
        LOG_INFO("    Run: python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_boundary");
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== MRoPE CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++;
    if (TestGetRopeIndexSimple()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage mrope_pid_simple' first");

    total++;
    if (TestGetRopeIndexNoImage()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage mrope_pid_no_img' first");

    total++;
    if (TestGetRopeIndexImageText()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage mrope_pid_image_text' first");

    total++;
    if (TestGetRopeIndexImageOnlyNoVisionStart()) passed++;

    total++;
    if (TestGetRopeIndexEdgeCases()) passed++;

    total++;
    if (TestMRoPECompute()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/python_reference/gen_cpu_reference.py --stage mrope_cos_sin' first");

    total++;
    if (TestGetRopeIndexMultiImage()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_multi_img' first");

    total++;
    if (TestGetRopeIndexChatTemplate()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/python_reference/gen_cpu_reference.py --stage mrope_pid_chat_template' first");

    total++;
    if (TestGetRopeIndexVisionStartBoundary()) passed++;

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
