/**
 * Level 1 CPU pure-function tests: SmartResize and related preprocessing functions.
 *
 * NO NPU required — CPU-only computations.
 * Compares against Python reference data generated by gen_cpu_reference.py.
 *
 * Prerequisites:
 *     python tests/gen_cpu_reference.py --stage smart_resize
 *     python tests/gen_cpu_reference.py --stage bicubic_preprocess
 *
 * Run: ./test_preprocess_cpu
 */

#include "adapters/qwen3vl_embedding/qwen3vl_preprocess.h"
#include "adapters/qwen3vl_embedding/qwen3vl_config.h"
#include "log/logger.h"

#include <cstdio>
#include <cstring>
#include <vector>
#include <cmath>
#include <cstdint>
#include <algorithm>
#include <string>

namespace {

// ── Load SmartResize reference data ────────────────────────
// Format: [count: int64] [data: int32[count]]  (in_h, in_w, out_h, out_w) pairs
struct SmartResizeRef {
    struct Case {
        int32_t in_h, in_w, out_h, out_w;
    };
    std::vector<Case> cases;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t count;
        if (fread(&count, sizeof(int64_t), 1, f) != 1) {
            fclose(f);
            return false;
        }
        std::vector<int32_t> data(count);
        if (fread(data.data(), sizeof(int32_t), count, f) != static_cast<size_t>(count)) {
            fclose(f);
            return false;
        }
        fclose(f);

        for (int64_t i = 0; i + 3 < count; i += 4) {
            cases.push_back({data[i], data[i+1], data[i+2], data[i+3]});
        }
        return true;
    }
};

// ── Generic [ndim, shape..., data] binary loader ─────────────────
struct LoadedArrayF32 {
    std::vector<int64_t> shape;
    std::vector<float> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(float), total, f) != static_cast<size_t>(total)) {
            fclose(f);
            return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayFp16 {
    std::vector<int64_t> shape;
    std::vector<uint16_t> data;  // raw fp16 bits

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(uint16_t), total, f) != static_cast<size_t>(total)) {
            fclose(f);
            return false;
        }
        fclose(f);
        return true;
    }
};

struct LoadedArrayI64 {
    std::vector<int64_t> shape;
    std::vector<int64_t> data;

    bool Load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            LOG_ERROR("Cannot open %s", path.c_str());
            return false;
        }
        int64_t ndim;
        if (fread(&ndim, sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
        shape.resize(ndim);
        int64_t total = 1;
        for (int64_t i = 0; i < ndim; i++) {
            if (fread(&shape[i], sizeof(int64_t), 1, f) != 1) { fclose(f); return false; }
            total *= shape[i];
        }
        data.resize(total);
        if (fread(data.data(), sizeof(int64_t), total, f) != static_cast<size_t>(total)) {
            fclose(f);
            return false;
        }
        fclose(f);
        return true;
    }
};

// IEEE-754 fp16 (uint16) → float32
float Fp16BitsToFloat(uint16_t h) {
    uint32_t sign = (h >> 15) & 0x1u;
    uint32_t exp  = (h >> 10) & 0x1Fu;
    uint32_t mant = h & 0x3FFu;
    uint32_t f;
    if (exp == 0) {
        if (mant == 0) {
            f = sign << 31;
        } else {
            // subnormal: normalize
            int e = -1;
            do {
                e++;
                mant <<= 1;
            } while ((mant & 0x400u) == 0);
            mant &= 0x3FFu;
            uint32_t exp_f = 127 - 15 - e;
            f = (sign << 31) | (exp_f << 23) | (mant << 13);
        }
    } else if (exp == 31) {
        // inf / NaN
        f = (sign << 31) | (0xFFu << 23) | (mant << 13);
    } else {
        uint32_t exp_f = exp - 15 + 127;
        f = (sign << 31) | (exp_f << 23) | (mant << 13);
    }
    float out;
    std::memcpy(&out, &f, sizeof(out));
    return out;
}

float CosineSim(const float* a, const float* b, int64_t n) {
    double dot = 0, na = 0, nb = 0;
    for (int64_t i = 0; i < n; i++) {
        dot += static_cast<double>(a[i]) * b[i];
        na  += static_cast<double>(a[i]) * a[i];
        nb  += static_cast<double>(b[i]) * b[i];
    }
    return static_cast<float>(dot / (std::sqrt(na) * std::sqrt(nb) + 1e-12));
}

float MaxAbsDiff(const float* a, const float* b, int64_t n) {
    float max_d = 0;
    for (int64_t i = 0; i < n; i++) {
        float d = std::fabs(a[i] - b[i]);
        if (d > max_d) max_d = d;
    }
    return max_d;
}

}  // namespace

// ═══════════════════════════════════════════════════════════════
// Test 1: SmartResize against Python reference
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeAgainstPython() {
    LOG_INFO("=== Test 1: SmartResize against Python reference ===");

    SmartResizeRef ref;
    if (!ref.Load("/tmp/cpu_smart_resize.bin")) {
        LOG_ERROR("SKIP: /tmp/cpu_smart_resize.bin not found");
        LOG_ERROR("  Run: python tests/gen_cpu_reference.py --stage smart_resize");
        return false;
    }

    int32_t factor = 32;
    int32_t min_px = 4096;
    int32_t max_px = 1843200;

    bool all_ok = true;
    for (size_t i = 0; i < ref.cases.size(); i++) {
        auto& c = ref.cases[i];
        int32_t nh = 0, nw = 0;
        atb_llm::adapters::SmartResize(c.in_h, c.in_w, factor, min_px, max_px, nh, nw);

        bool ok = (nh == c.out_h && nw == c.out_w);
        if (ok) {
            LOG_INFO("  [PASS] case %zu: (%d,%d) -> (%d,%d) = Python (%d,%d)",
                     i, c.in_h, c.in_w, nh, nw, c.out_h, c.out_w);
        } else {
            LOG_ERROR("  [FAIL] case %zu: (%d,%d) -> C++(%d,%d) != Python(%d,%d)",
                     i, c.in_h, c.in_w, nh, nw, c.out_h, c.out_w);
            all_ok = false;
        }
    }
    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 2: SmartResize — banker's rounding (regression)
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeBankers() {
    LOG_INFO("\n=== Test 2: SmartResize — banker's rounding regression ===");

    // The key regression case: 720 / 32 = 22.5
    // Standard rounding: round(22.5) = 23 → 23*32 = 736
    // Banker's rounding: round(22.5) = 22 (even!) → 22*32 = 704
    // Python uses banker's rounding → 704
    int32_t h = 720, w = 1000;
    int32_t factor = 32, min_px = 4096, max_px = 1280 * 720 * 4;
    int32_t nh = 0, nw = 0;

    atb_llm::adapters::SmartResize(h, w, factor, min_px, max_px, nh, nw);

    // With banker's rounding: 720/32=22.5→22, 1000/32=31.25→31, so 704x992
    // With standard rounding: 720/32=22.5→23, so 736x992
    // The expected (from Python): 704x992
    int32_t expected_h = 704, expected_w = 992;

    bool ok = (nh == expected_h && nw == expected_w);
    if (ok) {
        LOG_INFO("  [PASS] 720x1000 -> %dx%d (banker's rounding correct)", nh, nw);
    } else {
        LOG_ERROR("  [FAIL] 720x1000 -> %dx%d (expected %dx%d with banker's rounding)",
                 nh, nw, expected_h, expected_w);
    }
    return ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 3: SmartResize — boundary conditions [H1 hardening]
//
// Previously every case here LOG_INFO'd a [PASS] tag and the test
// returned `true` unconditionally — a classic fake-PASS. This version
// aggregates each case's pass/fail into `all_ok` and returns it so a
// regression actually trips the suite.
// ═══════════════════════════════════════════════════════════════
static bool TestSmartResizeBoundary() {
    LOG_INFO("\n=== Test 3: SmartResize — boundary conditions ===");

    int32_t factor = 32, min_px = 4096, max_px = 1843200;
    int32_t nh = 0, nw = 0;
    bool all_ok = true;

    // Case A: very small image (1, 1) — must be upscaled to satisfy min_pixels,
    //         dimensions divisible by factor, both non-zero.
    {
        atb_llm::adapters::SmartResize(1, 1, factor, min_px, max_px, nh, nw);
        int64_t area = static_cast<int64_t>(nh) * nw;
        bool ok = (area >= min_px) &&
                  (nh % factor == 0) && (nw % factor == 0) &&
                  (nh > 0) && (nw > 0);
        all_ok &= ok;
        LOG_INFO("  [%s] (1,1) → (%d,%d) area=%ld (>= %d, divisible by %d)",
                 ok ? "PASS" : "FAIL", nh, nw, area, min_px, factor);
    }

    // Case B: extreme aspect ratio (8, 1024) — dimensions divisible by factor,
    //         area within [min_pixels, max_pixels].
    {
        atb_llm::adapters::SmartResize(8, 1024, factor, min_px, max_px, nh, nw);
        int64_t area = static_cast<int64_t>(nh) * nw;
        bool ok = (nh % factor == 0) && (nw % factor == 0) &&
                  (area >= min_px) && (area <= max_px);
        all_ok &= ok;
        LOG_INFO("  [%s] (8,1024) → (%d,%d) area=%ld (factor=%d, in [%d,%d])",
                 ok ? "PASS" : "FAIL", nh, nw, area, factor, min_px, max_px);
    }

    // Case C: very large image (4000, 4000) — must be downscaled to satisfy
    //         max_pixels, dimensions divisible by factor.
    {
        atb_llm::adapters::SmartResize(4000, 4000, factor, min_px, max_px, nh, nw);
        int64_t area = static_cast<int64_t>(nh) * nw;
        bool ok = (area <= max_px) &&
                  (nh % factor == 0) && (nw % factor == 0);
        all_ok &= ok;
        LOG_INFO("  [%s] (4000,4000) → (%d,%d) area=%ld (<= %d, divisible by %d)",
                 ok ? "PASS" : "FAIL", nh, nw, area, max_px, factor);
    }

    // Case D: exactly factor×factor with min_pixels set to factor² so input
    //         already satisfies the lower bound — output must equal input.
    {
        int32_t local_min = factor * factor;  // 1024
        atb_llm::adapters::SmartResize(32, 32, factor, local_min, max_px, nh, nw);
        bool ok = (nh == factor) && (nw == factor);
        all_ok &= ok;
        LOG_INFO("  [%s] (32,32, min=%d) → (%d,%d) (expect %dx%d, unchanged)",
                 ok ? "PASS" : "FAIL", local_min, nh, nw, factor, factor);
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 4: BicubicResize bit-exact vs PIL reference [Batch C]
//
// The C++ CPU BicubicResize is now a fixed-point port of Pillow's 8bpc
// antialias resample (Batch A, zero-diff vs real PIL). The reference
// `bicubic_{name}_pil_output.bin` is genuine PIL.Image.resize(BICUBIC),
// so with identical uint8 inputs both sides MUST agree bit-for-bit
// (max_diff == 0). The gen script quantizes its source to uint8 before
// computing the reference, so we feed the dumped float32 values directly
// to BicubicResize after casting to uint8.
// ═══════════════════════════════════════════════════════════════
static bool TestBicubicVsPython() {
    LOG_INFO("\n=== Test 4: BicubicResize bit-exact vs PIL reference ===");

    struct Case {
        const char* name;
        int32_t channels;
        int32_t in_h, in_w;
        int32_t out_h, out_w;
    };
    Case cases[] = {
        {"2x2_to_4x4",              1, 2, 2,  4,  4},
        {"4x4_to_2x2",              1, 4, 4,  2,  2},
        {"random_8x8_to_16x16_3ch", 3, 8, 8, 16, 16},
    };

    bool all_ok = true;
    for (const auto& c : cases) {
        std::string in_path  = std::string("/tmp/bicubic_") + c.name + "_input.bin";
        std::string out_path = std::string("/tmp/bicubic_") + c.name + "_pil_output.bin";

        LoadedArrayF32 in_ref, out_ref;
        if (!in_ref.Load(in_path) || !out_ref.Load(out_path)) {
            LOG_ERROR("  [SKIP] %s: bin files missing — run "
                      "'python tests/gen_cpu_reference.py --stage bicubic_preprocess'", c.name);
            all_ok = false;
            continue;
        }

        int64_t in_elems  = static_cast<int64_t>(c.channels) * c.in_h  * c.in_w;
        int64_t out_elems = static_cast<int64_t>(c.channels) * c.out_h * c.out_w;
        if (static_cast<int64_t>(in_ref.data.size())  != in_elems ||
            static_cast<int64_t>(out_ref.data.size()) != out_elems) {
            LOG_ERROR("  [FAIL] %s: bin size mismatch (in=%zu expect %ld, out=%zu expect %ld)",
                     c.name, in_ref.data.size(), in_elems,
                     out_ref.data.size(), out_elems);
            all_ok = false;
            continue;
        }

        // Cast input float32 (already quantized in the gen script) → uint8.
        std::vector<uint8_t> in_u8(in_elems);
        for (int64_t i = 0; i < in_elems; i++) {
            float v = std::round(in_ref.data[i]);
            if (v < 0.0f) v = 0.0f;
            if (v > 255.0f) v = 255.0f;
            in_u8[i] = static_cast<uint8_t>(v);
        }

        std::vector<float> cpp_out(out_elems);
        atb_llm::adapters::BicubicResize(
            in_u8.data(), c.in_h, c.in_w, c.channels,
            c.out_h, c.out_w, cpp_out.data());

        float max_d = MaxAbsDiff(cpp_out.data(), out_ref.data.data(), out_elems);
        float cos_s = CosineSim(cpp_out.data(), out_ref.data.data(), out_elems);

        // Both sides run the SAME PIL 8bpc fixed-point resample on the SAME
        // uint8 input — bit-for-bit identical (max_diff == 0).
        bool ok = (max_d == 0.0f);
        all_ok &= ok;
        LOG_INFO("  [%s] %s: max_diff=%.6e cosine=%.6f (in=%dx%dx%d → %dx%d)",
                 ok ? "PASS" : "FAIL", c.name, max_d, cos_s,
                 c.channels, c.in_h, c.in_w, c.out_h, c.out_w);
        if (!ok) {
            // Show first divergent pixel
            for (int64_t i = 0; i < out_elems; i++) {
                float d = std::fabs(cpp_out[i] - out_ref.data[i]);
                if (d > 0.0f) {
                    LOG_ERROR("    first divergence at [%ld]: C++=%.6f PIL=%.6f diff=%.6e",
                             i, cpp_out[i], out_ref.data[i], d);
                    break;
                }
            }
        }
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 5: PreprocessImage end-to-end vs PIL reference [Batch C]
//
// The C++ CPU PreprocessImage and the Python PIL reference both quantize
// the identical fp32 pixel_values to fp16, so the dumped fp16 bits must be
// bit-for-bit equal (max_diff == 0). cos >= 0.99999 is a redundant guard.
// grid_thw must be exactly equal. The `down_144x272` case forces the
// genuine AA downsample path (144→128, 272→256).
// ═══════════════════════════════════════════════════════════════
static bool TestPreprocessImageVsPython() {
    LOG_INFO("\n=== Test 5: PreprocessImage bit-exact vs PIL reference ===");

    struct Case {
        const char* name;
        int32_t channels;
        int32_t height, width;
    };
    Case cases[] = {
        {"gradient_64x64", 3, 64, 64},
        {"random_96x96",   3, 96, 96},
        {"down_144x272",   3, 144, 272},
    };

    atb_llm::adapters::Qwen3VLConfig cfg{};
    // Mirror Python defaults: patch=16, temporal=2, merge=2, min/max_pixels.
    cfg.pp_patch_size           = 16;
    cfg.pp_temporal_patch_size  = 2;
    cfg.pp_merge_size           = 2;
    cfg.pp_min_pixels           = 4096;
    cfg.pp_max_pixels           = 1843200;

    bool all_ok = true;
    for (const auto& c : cases) {
        std::string in_path   = std::string("/tmp/preprocess_") + c.name + "_input.bin";
        std::string out_path  = std::string("/tmp/preprocess_") + c.name + "_pil_output.bin";
        std::string grid_path = std::string("/tmp/preprocess_") + c.name + "_grid.bin";

        LoadedArrayF32  in_ref;       // input stored as float32 view of uint8
        LoadedArrayFp16 out_ref_fp16;
        LoadedArrayI64  grid_ref;
        if (!in_ref.Load(in_path) ||
            !out_ref_fp16.Load(out_path) ||
            !grid_ref.Load(grid_path)) {
            LOG_ERROR("  [SKIP] %s: bin files missing — run "
                      "'python tests/gen_cpu_reference.py --stage bicubic_preprocess'", c.name);
            all_ok = false;
            continue;
        }

        int64_t in_elems = static_cast<int64_t>(c.channels) * c.height * c.width;
        if (static_cast<int64_t>(in_ref.data.size()) != in_elems) {
            LOG_ERROR("  [FAIL] %s: input bin size mismatch %zu vs expect %ld",
                     c.name, in_ref.data.size(), in_elems);
            all_ok = false;
            continue;
        }

        std::vector<uint8_t> img_u8(in_elems);
        for (int64_t i = 0; i < in_elems; i++) {
            float v = std::round(in_ref.data[i]);
            if (v < 0.0f) v = 0.0f;
            if (v > 255.0f) v = 255.0f;
            img_u8[i] = static_cast<uint8_t>(v);
        }

        // Output buffer: oversize to the reference's flattened size — the
        // adapter writes exactly num_patches * patch_dim fp16 elements.
        std::vector<uint16_t> cpp_pixels(out_ref_fp16.data.size());
        int64_t num_patches = 0;
        int64_t grid_thw[3] = {0, 0, 0};

        auto status = atb_llm::adapters::PreprocessImage(
            img_u8.data(), c.channels, c.height, c.width,
            cfg, cpp_pixels.data(), num_patches, grid_thw);

        if (status != atb_llm::STATUS_OK) {
            LOG_ERROR("  [FAIL] %s: PreprocessImage returned status=%d",
                     c.name, static_cast<int>(status));
            all_ok = false;
            continue;
        }

        // ── Check grid_thw equality (must be exact) ──
        if (grid_ref.data.size() < 3) {
            LOG_ERROR("  [FAIL] %s: ref grid has < 3 entries", c.name);
            all_ok = false;
            continue;
        }
        bool grid_ok = (grid_thw[0] == grid_ref.data[0]) &&
                       (grid_thw[1] == grid_ref.data[1]) &&
                       (grid_thw[2] == grid_ref.data[2]);
        if (!grid_ok) {
            LOG_ERROR("  [FAIL] %s: grid_thw C++=[%ld,%ld,%ld] Python=[%ld,%ld,%ld]",
                     c.name, grid_thw[0], grid_thw[1], grid_thw[2],
                     grid_ref.data[0], grid_ref.data[1], grid_ref.data[2]);
            all_ok = false;
            continue;
        }

        int64_t ref_total = static_cast<int64_t>(out_ref_fp16.data.size());
        int64_t expected_total = num_patches *
            (static_cast<int64_t>(c.channels) * cfg.pp_temporal_patch_size *
             cfg.pp_patch_size * cfg.pp_patch_size);
        if (expected_total != ref_total) {
            LOG_ERROR("  [FAIL] %s: num_patches=%ld * patch_dim != ref total (%ld vs %ld)",
                     c.name, num_patches, expected_total, ref_total);
            all_ok = false;
            continue;
        }

        // Decode both sides to fp32 and compare. Both sides quantize the same
        // fp32 pixel_values to fp16, so the buffers must be bit-for-bit equal.
        std::vector<float> cpp_f32(ref_total), ref_f32(ref_total);
        bool bits_equal = true;
        for (int64_t i = 0; i < ref_total; i++) {
            if (cpp_pixels[i] != out_ref_fp16.data[i]) bits_equal = false;
            cpp_f32[i] = Fp16BitsToFloat(cpp_pixels[i]);
            ref_f32[i] = Fp16BitsToFloat(out_ref_fp16.data[i]);
        }
        float cos_s = CosineSim(cpp_f32.data(), ref_f32.data(), ref_total);
        float md    = MaxAbsDiff(cpp_f32.data(), ref_f32.data(), ref_total);

        // fp16 bit-level equality is the primary assertion; cos>=0.99999 is a
        // redundant guard.
        bool ok = bits_equal && (md == 0.0f) && (cos_s >= 0.99999f);
        all_ok &= ok;
        LOG_INFO("  [%s] %s: grid=[%ld,%ld,%ld] patches=%ld cosine=%.6f max_diff=%.6e bits_equal=%d",
                 ok ? "PASS" : "FAIL", c.name,
                 grid_thw[0], grid_thw[1], grid_thw[2], num_patches, cos_s, md, bits_equal ? 1 : 0);
        if (!ok) {
            for (int64_t i = 0; i < ref_total; i++) {
                if (cpp_pixels[i] != out_ref_fp16.data[i]) {
                    LOG_ERROR("    first divergence at [%ld]: C++ bits=0x%04x (%.6f) PIL bits=0x%04x (%.6f)",
                             i, cpp_pixels[i], cpp_f32[i], out_ref_fp16.data[i], ref_f32[i]);
                    break;
                }
            }
        }
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Test 7: BicubicResize bit-exact vs PIL at production resolutions [Batch C]
//
// Level-1 CPU-only gate (no NPU). Covers the real engine resize sizes:
//   - prod_416x672   → identity (416 stays, 672→672), no resample
//   - prod_720x1280  → mixed axis (720→704 downsample, 1280→1280)
//   - prod_1080x1920 → dual-axis downsample (the AA regime)
//   - prod_1440x2560 → dual-axis downsample (noise worst-case)
// Output dims are read from the PIL reference .bin shape, so the test
// tracks SmartResize automatically. The C++ CPU BicubicResize is the
// PIL 8bpc fixed-point port, so each case must be bit-for-bit identical
// (MaxAbsDiff == 0).
// ═══════════════════════════════════════════════════════════════
static bool TestBicubicProdVsPIL() {
    LOG_INFO("\n=== Test 7: BicubicResize bit-exact vs PIL (production resolutions) ===");

    struct Case {
        const char* name;
        int32_t channels;
        int32_t in_h, in_w;
    };
    Case cases[] = {
        {"prod_416x672",   3, 416,  672},
        {"prod_720x1280",  3, 720,  1280},
        {"prod_1080x1920", 3, 1080, 1920},
        {"prod_1440x2560", 3, 1440, 2560},
    };

    bool all_ok = true;
    for (const auto& c : cases) {
        std::string in_path  = std::string("/tmp/bicubic_") + c.name + "_input.bin";
        std::string pil_path = std::string("/tmp/bicubic_") + c.name + "_pil_output.bin";

        LoadedArrayF32 in_ref, pil_ref;
        if (!in_ref.Load(in_path) || !pil_ref.Load(pil_path)) {
            LOG_ERROR("  [SKIP] %s: bin files missing — run "
                      "'python tests/python_reference/gen_cpu_reference.py'", c.name);
            all_ok = false;
            continue;
        }

        if (pil_ref.shape.size() != 3 || in_ref.shape.size() != 3) {
            LOG_ERROR("  [FAIL] %s: unexpected ndim (in=%zu pil=%zu)",
                      c.name, in_ref.shape.size(), pil_ref.shape.size());
            all_ok = false;
            continue;
        }

        // Output dims follow SmartResize via the PIL ref shape.
        int32_t out_h = static_cast<int32_t>(pil_ref.shape[1]);
        int32_t out_w = static_cast<int32_t>(pil_ref.shape[2]);

        int64_t in_elems  = static_cast<int64_t>(c.channels) * c.in_h  * c.in_w;
        int64_t out_elems = static_cast<int64_t>(c.channels) * out_h * out_w;
        if (static_cast<int64_t>(in_ref.data.size())  != in_elems ||
            static_cast<int64_t>(pil_ref.data.size()) != out_elems) {
            LOG_ERROR("  [FAIL] %s: bin size mismatch (in=%zu expect %ld, pil=%zu expect %ld)",
                     c.name, in_ref.data.size(), in_elems,
                     pil_ref.data.size(), out_elems);
            all_ok = false;
            continue;
        }

        // Cast input float32 (already quantized in the gen script) → uint8.
        std::vector<uint8_t> in_u8(in_elems);
        for (int64_t i = 0; i < in_elems; i++) {
            float v = std::round(in_ref.data[i]);
            if (v < 0.0f) v = 0.0f;
            if (v > 255.0f) v = 255.0f;
            in_u8[i] = static_cast<uint8_t>(v);
        }

        std::vector<float> cpp_out(out_elems);
        atb_llm::adapters::BicubicResize(
            in_u8.data(), c.in_h, c.in_w, c.channels,
            out_h, out_w, cpp_out.data());

        float max_d = MaxAbsDiff(cpp_out.data(), pil_ref.data.data(), out_elems);
        bool ok = (max_d == 0.0f);
        all_ok &= ok;
        LOG_INFO("  [%s] %s: max_diff=%.6e (in=%dx%dx%d → %dx%d)",
                 ok ? "PASS" : "FAIL", c.name, max_d,
                 c.channels, c.in_h, c.in_w, out_h, out_w);
        if (!ok) {
            for (int64_t i = 0; i < out_elems; i++) {
                float d = std::fabs(cpp_out[i] - pil_ref.data[i]);
                if (d > 0.0f) {
                    LOG_ERROR("    first divergence at [%ld]: C++=%.6f PIL=%.6f diff=%.6e",
                             i, cpp_out[i], pil_ref.data[i], d);
                    break;
                }
            }
        }
    }

    return all_ok;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

int main() {
    LOG_INFO("=== Preprocess CPU Tests (Level 1) ===\n");

    int passed = 0, total = 0;

    total++;
    if (TestSmartResizeAgainstPython()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage smart_resize' first");

    total++;
    if (TestSmartResizeBankers()) passed++;

    total++;
    if (TestSmartResizeBoundary()) passed++;

    total++;
    if (TestBicubicVsPython()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage bicubic_preprocess' first");

    total++;
    if (TestPreprocessImageVsPython()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/gen_cpu_reference.py --stage bicubic_preprocess' first");

    total++;
    if (TestBicubicProdVsPIL()) passed++;
    else LOG_ERROR("  Hint: run 'python tests/python_reference/gen_cpu_reference.py' first");

    LOG_INFO("\n=== Summary: %d/%d tests passed ===", passed, total);
    return (passed == total) ? 0 : 1;
}
